-- Agentic Marketing System — Phase 3 Controlled Work Orders
-- Additive only. No existing CRM, Marketing plan, Lead, client, Contract, Financial,
-- Client Documentation, Client Portal, Meta/CAPI, provider-profile, source, claim,
-- Brand Studio, or audit record is altered. No provider action or paid-media spend occurs.
CREATE TABLE IF NOT EXISTS `marketing_work_orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `workOrderKey` VARCHAR(96) NOT NULL,
  `idempotencyKey` VARCHAR(128) NOT NULL,
  `workType` VARCHAR(48) NOT NULL,
  `title` VARCHAR(300) NOT NULL,
  `programKey` VARCHAR(96) NULL,
  `objective` VARCHAR(500) NOT NULL,
  `brief` MEDIUMTEXT NOT NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'draft',
  `requestedProviderAlias` VARCHAR(96) NOT NULL,
  `providerModelId` VARCHAR(160) NULL,
  `brandBookId` INT NULL,
  `brandBookVersion` INT NULL,
  `knowledgeClaimIdsJson` MEDIUMTEXT NOT NULL,
  `inputArtifactIdsJson` MEDIUMTEXT NOT NULL,
  `outputSchemaJson` MEDIUMTEXT NOT NULL,
  `allowedNextStatesJson` MEDIUMTEXT NOT NULL,
  `costCeilingUsd` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `estimatedCostUsd` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `actualCostUsd` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `currency` VARCHAR(8) NOT NULL DEFAULT 'USD',
  `maxIterations` INT NOT NULL DEFAULT 1,
  `iterationCount` INT NOT NULL DEFAULT 0,
  `createdByUserId` INT NOT NULL,
  `submittedAt` BIGINT NULL,
  `reviewedByUserId` INT NULL,
  `reviewedAt` BIGINT NULL,
  `reviewNote` TEXT NULL,
  `lastDryRunAt` BIGINT NULL,
  `cancelledByUserId` INT NULL,
  `cancelledAt` BIGINT NULL,
  `createdAt` BIGINT NOT NULL,
  `updatedAt` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `marketing_work_order_key_unique` (`workOrderKey`),
  UNIQUE KEY `marketing_work_order_idempotency_unique` (`idempotencyKey`),
  KEY `marketing_work_order_status_updated_idx` (`status`, `updatedAt`),
  KEY `marketing_work_order_creator_status_idx` (`createdByUserId`, `status`, `updatedAt`),
  KEY `marketing_work_order_program_idx` (`programKey`, `updatedAt`)
);
CREATE TABLE IF NOT EXISTS `marketing_work_order_artifacts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `workOrderId` INT NOT NULL,
  `artifactType` VARCHAR(64) NOT NULL,
  `state` VARCHAR(32) NOT NULL DEFAULT 'dry_run',
  `label` VARCHAR(300) NOT NULL,
  `artifactPayloadJson` MEDIUMTEXT NOT NULL,
  `contentHash` VARCHAR(64) NOT NULL,
  `providerAlias` VARCHAR(96) NULL,
  `providerModelId` VARCHAR(160) NULL,
  `promptTemplateVersion` VARCHAR(64) NOT NULL,
  `sourceClaimIdsJson` MEDIUMTEXT NOT NULL,
  `sourceSnapshotHashesJson` MEDIUMTEXT NOT NULL,
  `confidence` DECIMAL(5,4) NULL,
  `estimatedCostUsd` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `actualCostUsd` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `errorSummary` TEXT NULL,
  `createdByUserId` INT NOT NULL,
  `createdAt` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `marketing_work_order_artifact_hash_unique` (`contentHash`),
  KEY `marketing_work_order_artifact_order_idx` (`workOrderId`, `createdAt`),
  KEY `marketing_work_order_artifact_state_idx` (`state`, `createdAt`)
);
CREATE TABLE IF NOT EXISTS `marketing_work_order_events` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `workOrderId` INT NOT NULL,
  `action` VARCHAR(64) NOT NULL,
  `fromStatus` VARCHAR(32) NULL,
  `toStatus` VARCHAR(32) NULL,
  `reason` TEXT NULL,
  `payloadJson` MEDIUMTEXT NOT NULL,
  `actorUserId` INT NOT NULL,
  `createdAt` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `marketing_work_order_event_order_idx` (`workOrderId`, `createdAt`),
  KEY `marketing_work_order_event_action_idx` (`action`, `createdAt`)
);
CREATE TABLE IF NOT EXISTS `marketing_work_order_cost_ledger` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `workOrderId` INT NOT NULL,
  `entryKey` VARCHAR(128) NOT NULL,
  `entryType` VARCHAR(32) NOT NULL,
  `amountUsd` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `currency` VARCHAR(8) NOT NULL DEFAULT 'USD',
  `providerAlias` VARCHAR(96) NULL,
  `note` TEXT NULL,
  `createdByUserId` INT NOT NULL,
  `createdAt` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `marketing_work_order_cost_entry_unique` (`entryKey`),
  KEY `marketing_work_order_cost_order_idx` (`workOrderId`, `createdAt`),
  KEY `marketing_work_order_cost_type_idx` (`entryType`, `createdAt`)
);
