-- Agentic Marketing System — Phase 4 Content Studio & Approval Inbox
-- Additive only. No existing CRM, Lead, client, Contract, Financial, Client Documentation,
-- Client Portal, chat, Meta/CAPI, provider, source, claim, Brand Book, work-order or audit
-- record is altered. These tables do not execute models, generate media, publish content,
-- activate campaigns, contact anyone, or reserve/record paid-media spend.
CREATE TABLE IF NOT EXISTS `marketing_content_packets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rootPacketKey` VARCHAR(96) NOT NULL,
  `versionNumber` INT NOT NULL DEFAULT 1,
  `previousPacketId` INT NULL,
  `workOrderId` INT NOT NULL,
  `workOrderKey` VARCHAR(96) NOT NULL,
  `contentType` VARCHAR(48) NOT NULL,
  `title` VARCHAR(300) NOT NULL,
  `programKey` VARCHAR(96) NOT NULL,
  `platformJson` MEDIUMTEXT NOT NULL,
  `funnelStage` VARCHAR(64) NOT NULL,
  `audience` VARCHAR(500) NOT NULL,
  `objective` VARCHAR(500) NOT NULL,
  `arabicCopy` MEDIUMTEXT NOT NULL,
  `englishCopy` MEDIUMTEXT NULL,
  `caption` MEDIUMTEXT NULL,
  `cta` VARCHAR(500) NOT NULL,
  `landingDestination` VARCHAR(2000) NULL,
  `scheduledFor` BIGINT NULL,
  `claimIdsJson` MEDIUMTEXT NOT NULL,
  `sourceSnapshotHashesJson` MEDIUMTEXT NOT NULL,
  `visualBrief` MEDIUMTEXT NULL,
  `payloadJson` MEDIUMTEXT NOT NULL,
  `outputSchemaJson` MEDIUMTEXT NOT NULL,
  `previewUrl` VARCHAR(2000) NULL,
  `previewHash` VARCHAR(64) NULL,
  `qaResultsJson` MEDIUMTEXT NOT NULL,
  `exceptionalClaim` BOOLEAN NOT NULL DEFAULT FALSE,
  `status` VARCHAR(32) NOT NULL DEFAULT 'draft',
  `contentHash` VARCHAR(64) NOT NULL,
  `changeSummary` TEXT NULL,
  `blockedReason` TEXT NULL,
  `createdByUserId` INT NOT NULL,
  `lastEditedByUserId` INT NOT NULL,
  `approvedByUserId` INT NULL,
  `approvedAt` BIGINT NULL,
  `stoppedByUserId` INT NULL,
  `stoppedAt` BIGINT NULL,
  `createdAt` BIGINT NOT NULL,
  `updatedAt` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `marketing_content_packet_root_version_unique` (`rootPacketKey`, `versionNumber`),
  UNIQUE KEY `marketing_content_packet_content_hash_unique` (`contentHash`),
  KEY `marketing_content_packet_status_updated_idx` (`status`, `updatedAt`),
  KEY `marketing_content_packet_work_order_idx` (`workOrderId`, `updatedAt`),
  KEY `marketing_content_packet_program_status_idx` (`programKey`, `status`, `updatedAt`)
);
CREATE TABLE IF NOT EXISTS `marketing_content_review_events` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `packetId` INT NOT NULL,
  `action` VARCHAR(64) NOT NULL,
  `fromStatus` VARCHAR(32) NULL,
  `toStatus` VARCHAR(32) NULL,
  `feedback` MEDIUMTEXT NULL,
  `annotationsJson` MEDIUMTEXT NOT NULL,
  `payloadJson` MEDIUMTEXT NOT NULL,
  `actorUserId` INT NOT NULL,
  `createdAt` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `marketing_content_review_event_packet_idx` (`packetId`, `createdAt`),
  KEY `marketing_content_review_event_action_idx` (`action`, `createdAt`)
);
CREATE TABLE IF NOT EXISTS `marketing_content_approval_batches` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `batchKey` VARCHAR(96) NOT NULL,
  `packetIdsJson` MEDIUMTEXT NOT NULL,
  `packetContentHashesJson` MEDIUMTEXT NOT NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'approved',
  `ownerNote` MEDIUMTEXT NOT NULL,
  `approvedByUserId` INT NOT NULL,
  `approvedAt` BIGINT NOT NULL,
  `createdAt` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `marketing_content_approval_batch_key_unique` (`batchKey`),
  KEY `marketing_content_approval_batch_status_idx` (`status`, `approvedAt`)
);
