-- ELEVAY Agentic Marketing: review-only reel composition and future social release governance.
-- Additive control plane only. No provider credentials, publication calls, Meta campaign/ad/spend,
-- CAPI, Lead/client data, or media bytes are stored in this migration.

CREATE TABLE IF NOT EXISTS `marketing_reel_composition_input_approvals` (
  `id` int NOT NULL AUTO_INCREMENT,
  `approvalKey` varchar(160) NOT NULL,
  `weeklyItemId` int NOT NULL,
  `assetType` varchar(32) NOT NULL,
  `assetUrl` varchar(2000) NOT NULL,
  `assetSha256` varchar(64) NOT NULL,
  `mimeType` varchar(128) NOT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'approved',
  `approvedByUserId` int NOT NULL,
  `approvedAt` bigint NOT NULL,
  `supersededAt` bigint NULL,
  `createdAt` bigint NOT NULL,
  `updatedAt` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `marketing_reel_composition_input_approval_key_unique` (`approvalKey`),
  KEY `marketing_reel_composition_input_item_type_status_idx` (`weeklyItemId`, `assetType`, `status`, `updatedAt`)
);

CREATE TABLE IF NOT EXISTS `marketing_reel_compositions` (
  `id` int NOT NULL AUTO_INCREMENT,
  `compositionKey` varchar(160) NOT NULL,
  `weeklyItemId` int NOT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'queued',
  `sourceVideoApprovalId` int NOT NULL,
  `narrationApprovalId` int NOT NULL,
  `sourceDurationMs` int NOT NULL,
  `sourceWidth` int NOT NULL,
  `sourceHeight` int NOT NULL,
  `narrationDurationMs` int NOT NULL,
  `outputStorageKey` varchar(768) NULL,
  `outputUrl` varchar(2000) NULL,
  `outputSha256` varchar(64) NULL,
  `outputBytes` bigint NULL,
  `outputDurationMs` int NULL,
  `outputVideoCodec` varchar(64) NULL,
  `outputAudioCodec` varchar(64) NULL,
  `inputManifestJson` mediumtext NOT NULL,
  `errorSummary` text NULL,
  `requestedByUserId` int NOT NULL,
  `createdAt` bigint NOT NULL,
  `completedAt` bigint NULL,
  `updatedAt` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `marketing_reel_composition_key_unique` (`compositionKey`),
  KEY `marketing_reel_composition_item_status_idx` (`weeklyItemId`, `status`, `updatedAt`)
);

CREATE TABLE IF NOT EXISTS `marketing_social_release_authorizations` (
  `id` int NOT NULL AUTO_INCREMENT,
  `authorizationKey` varchar(200) NOT NULL,
  `weeklyItemId` int NOT NULL,
  `platform` varchar(32) NOT NULL,
  `previewUrl` varchar(2000) NOT NULL,
  `previewHash` varchar(64) NOT NULL,
  `individualApprovalAt` bigint NOT NULL,
  `feedbackResolvedAt` bigint NOT NULL,
  `trailingWindowStartAt` bigint NOT NULL,
  `trailingWindowEndAt` bigint NOT NULL,
  `eligibleItemCount` int NOT NULL,
  `approvalScorePercent` decimal(6,2) NOT NULL,
  `thresholdPercent` int NOT NULL DEFAULT 90,
  `status` varchar(32) NOT NULL DEFAULT 'authorized_pending_channel_setup',
  `authorizedByUserId` int NOT NULL,
  `authorizedAt` bigint NOT NULL,
  `revokedByUserId` int NULL,
  `revokedAt` bigint NULL,
  `revokeReason` text NULL,
  `externalPublicationId` varchar(255) NULL,
  `lastReconciledAt` bigint NULL,
  `createdAt` bigint NOT NULL,
  `updatedAt` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `marketing_social_release_authorization_key_unique` (`authorizationKey`),
  KEY `marketing_social_release_item_platform_idx` (`weeklyItemId`, `platform`, `status`, `updatedAt`)
);
