import { useMemo, useState } from "react";
import { AlertTriangle, BellRing, ExternalLink, FileCheck2, KeyRound, Link2, MessageSquare, Plus, RefreshCw, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { useAuth } from "@/_core/hooks/useAuth";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";

type Tab = "accounts" | "programs" | "providers" | "sync";
type ApplicationRef = { publicId: string; label: string | null };
const EMPTY_UUID = "00000000-0000-0000-0000-000000000000";

export default function ClientPortalAdmin() {
  const { user } = useAuth();
  const isAdmin = user?.role === "admin";
  const [tab, setTab] = useState<Tab>("accounts");
  const [createOpen, setCreateOpen] = useState(false);
  const [credentials, setCredentials] = useState<{ username: string; email: string; temporaryPassword: string } | null>(null);
  const [messageApplication, setMessageApplication] = useState<ApplicationRef | null>(null);
  const [documentApplication, setDocumentApplication] = useState<ApplicationRef | null>(null);
  const [reply, setReply] = useState("");
  const [replyVisibility, setReplyVisibility] = useState<"client" | "internal">("client");
  const [programEdit, setProgramEdit] = useState<any | null>(null);
  const [providerEdit, setProviderEdit] = useState<any | null>(null);

  const accountsQuery = trpc.clientPortalAdmin.listAccounts.useQuery(undefined, { enabled: isAdmin });
  const casesQuery = trpc.clientPortalAdmin.listClientCases.useQuery(undefined, { enabled: isAdmin && createOpen });
  const programsQuery = trpc.clientPortalAdmin.listPrograms.useQuery(undefined, { enabled: isAdmin && tab === "programs" });
  const providersQuery = trpc.clientPortalAdmin.listProviders.useQuery(undefined, { enabled: isAdmin && tab === "providers" });
  const syncQuery = trpc.clientPortalAdmin.contentSyncStatus.useQuery(undefined, { enabled: isAdmin && tab === "sync" });
  const messagesQuery = trpc.clientPortalAdmin.listMessages.useQuery({ applicationPublicId: messageApplication?.publicId || EMPTY_UUID }, { enabled: Boolean(messageApplication) });

  const setStatus = trpc.clientPortalAdmin.setAccountStatus.useMutation({ onSuccess: () => accountsQuery.refetch(), onError: error => toast.error(error.message) });
  const forceLogout = trpc.clientPortalAdmin.forceLogout.useMutation({ onSuccess: () => { toast.success("All client sessions revoked"); accountsQuery.refetch(); }, onError: error => toast.error(error.message) });
  const resetPassword = trpc.clientPortalAdmin.resetTemporaryPassword.useMutation({ onSuccess: data => setCredentials({ username: "Existing account", email: "Share securely with the client", temporaryPassword: data.temporaryPassword }), onError: error => toast.error(error.message) });
  const sendReply = trpc.clientPortalAdmin.replyToClient.useMutation({ onSuccess: () => { setReply(""); messagesQuery.refetch(); toast.success(replyVisibility === "client" ? "Reply sent to the client" : "Internal note added"); }, onError: error => toast.error(error.message) });
  const saveProgram = trpc.clientPortalAdmin.updateProgram.useMutation({ onSuccess: () => { setProgramEdit(null); programsQuery.refetch(); toast.success("Program updated"); }, onError: error => toast.error(error.message) });
  const saveProvider = trpc.clientPortalAdmin.saveProvider.useMutation({ onSuccess: () => { setProviderEdit(null); providersQuery.refetch(); toast.success("Provider saved"); }, onError: error => toast.error(error.message) });
  const runSync = trpc.clientPortalAdmin.runContentSync.useMutation({ onSuccess: data => { toast.success(`Sync complete: ${data.programsFound} programs found`); syncQuery.refetch(); programsQuery.refetch(); }, onError: error => toast.error(error.message) });

  if (!isAdmin) return <div className="min-h-[60vh] flex flex-col items-center justify-center gap-3"><AlertTriangle className="h-12 w-12 text-amber-500"/><h1 className="text-xl font-semibold">Admin access required</h1></div>;

  return <div className="p-4 md:p-6 space-y-6 max-w-7xl mx-auto">
    <header className="rounded-2xl bg-gradient-to-r from-[#10263d] to-[#1d5364] text-white p-6 shadow-lg"><div className="flex items-center gap-3"><ShieldCheck className="h-8 w-8 text-[#8ed7e7]"/><div><h1 className="text-2xl font-bold">ELEVAY Client Portal</h1><p className="text-sm text-white/70 mt-1">Secure client access, documents, content, providers, and communications</p></div></div></header>
    <nav className="flex gap-2 overflow-x-auto pb-1" aria-label="Client portal administration sections">{(["accounts", "programs", "providers", "sync"] as Tab[]).map(item => <Button key={item} variant={tab === item ? "default" : "outline"} onClick={() => setTab(item)} className="capitalize">{item}</Button>)}</nav>

    {tab === "accounts" && <section className="space-y-4">
      <div className="flex flex-wrap justify-between items-center gap-3"><div><h2 className="text-xl font-semibold">Client accounts</h2><p className="text-sm text-muted-foreground">Create the username and password, then select the CRM documentation folder(s) this client may access.</p></div><Button onClick={() => setCreateOpen(true)} className="gap-2"><Plus className="h-4 w-4"/>Create client access</Button></div>
      <div className="grid gap-3">
        {accountsQuery.isLoading && <PanelMessage>Loading client accounts…</PanelMessage>}
        {!accountsQuery.isLoading && !accountsQuery.data?.length && <PanelMessage>No client portal accounts yet.</PanelMessage>}
        {accountsQuery.data?.map(account => <article key={account.publicId} className="bg-card text-card-foreground rounded-xl border p-4 shadow-sm space-y-4">
          <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4"><div className="min-w-0"><div className="flex items-center gap-2 flex-wrap"><h3 className="font-semibold text-lg">{account.clientName}</h3><Badge variant={account.status === "active" ? "default" : "secondary"}>{account.status}</Badge></div><p className="text-sm text-muted-foreground">{account.clientCode} · {account.username} · {account.email}</p><p className="text-xs text-muted-foreground mt-1">{account.applications.length} application{account.applications.length === 1 ? "" : "s"} · {account.activeSessions} active device{account.activeSessions === 1 ? "" : "s"}</p></div><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" className="gap-1.5" onClick={() => resetPassword.mutate({ publicId: account.publicId })}><KeyRound className="h-4 w-4"/>Reset password</Button><Button size="sm" variant="outline" className="gap-1.5" onClick={() => forceLogout.mutate({ publicId: account.publicId })}><Link2 className="h-4 w-4"/>Force logout</Button><Button size="sm" variant={account.status === "active" ? "destructive" : "default"} onClick={() => setStatus.mutate({ publicId: account.publicId, status: account.status === "active" ? "disabled" : "active" })}>{account.status === "active" ? "Disable" : "Enable"}</Button></div></div>
          <div className="rounded-lg bg-muted/40 p-3 space-y-2"><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Applications</p>{account.applications.map(application => <div key={application.publicId} className="flex flex-wrap items-center justify-between gap-2 rounded-md bg-background border px-3 py-2"><span className="text-sm font-medium">{application.label || "Application"}{application.isPrimary && <Badge variant="outline" className="ml-2">Primary</Badge>}</span><span className="flex gap-2"><Button size="sm" variant="ghost" className="gap-1" onClick={() => setMessageApplication(application)}><MessageSquare className="h-4 w-4"/>Messages</Button><Button size="sm" variant="ghost" className="gap-1" onClick={() => setDocumentApplication(application)}><FileCheck2 className="h-4 w-4"/>Documents</Button></span></div>)}</div>
        </article>)}
      </div>
    </section>}

    {tab === "programs" && <section className="space-y-4"><div><h2 className="text-xl font-semibold">Residency & citizenship programs</h2><p className="text-sm text-muted-foreground">Website-synchronized content with protected manual overrides.</p></div><div className="grid sm:grid-cols-2 xl:grid-cols-3 gap-3">{programsQuery.data?.map(program => <button key={program.publicId} onClick={() => setProgramEdit(program)} className="text-left bg-card text-card-foreground rounded-xl border p-4 hover:shadow-md transition-shadow"><div className="flex justify-between gap-2"><Badge variant="outline" className="capitalize">{program.category}</Badge>{program.isOverridden && <Badge variant="secondary">Manual override</Badge>}</div><h3 className="font-semibold mt-3">{program.nameEn}</h3><p dir="rtl" className="text-sm text-muted-foreground mt-1">{program.nameAr || "Arabic name not set"}</p><p className="text-xs text-muted-foreground mt-3 line-clamp-2">{program.summaryEn}</p></button>)}</div></section>}

    {tab === "providers" && <section className="space-y-4"><div className="flex justify-between items-center gap-3"><div><h2 className="text-xl font-semibold">Service providers</h2><p className="text-sm text-muted-foreground">Lawyers, accountants, and service facilitators displayed in the client app.</p></div><Button onClick={() => setProviderEdit({ providerType: "lawyer", name: "", country: "", city: "", description: "", services: [], languages: [], displayOrder: 0, isActive: true })}><Plus className="h-4 w-4 mr-2"/>Add provider</Button></div><div className="grid sm:grid-cols-2 xl:grid-cols-3 gap-3">{providersQuery.data?.map(provider => <button key={provider.publicId} onClick={() => setProviderEdit(provider)} className="text-left bg-card text-card-foreground rounded-xl border p-4 hover:shadow-md transition-shadow"><div className="flex justify-between"><Badge className="capitalize">{provider.providerType.replaceAll("_", " ")}</Badge><Badge variant={provider.isActive ? "outline" : "secondary"}>{provider.isActive ? "Active" : "Hidden"}</Badge></div><h3 className="font-semibold mt-3">{provider.name}</h3><p className="text-sm text-muted-foreground">{provider.city ? `${provider.city}, ` : ""}{provider.country}</p><p className="text-xs text-muted-foreground mt-3 line-clamp-2">{provider.description}</p></button>)}</div></section>}

    {tab === "sync" && <section className="grid lg:grid-cols-[1fr_1.5fr] gap-4"><div className="rounded-xl border bg-card text-card-foreground p-5"><BellRing className="h-7 w-7 text-[#2c91a9]"/><h2 className="text-xl font-semibold mt-3">Friday content sync</h2><p className="text-sm text-muted-foreground mt-2">{syncQuery.data?.settings?.scheduleCronTaskUid ? "Runs every Friday around midnight–01:00 Cairo time. Failed runs keep the last valid program content." : "Manual synchronization is available. The managed Friday schedule activates after this version is deployed."}</p><dl className="mt-4 space-y-2 text-sm"><div className="flex justify-between gap-4"><dt>Schedule</dt><dd><Badge variant={syncQuery.data?.settings?.scheduleCronTaskUid ? "default" : "secondary"}>{syncQuery.data?.settings?.scheduleCronTaskUid ? "Active" : "Pending deploy"}</Badge></dd></div><div className="flex justify-between gap-4"><dt>Last success</dt><dd>{syncQuery.data?.settings?.lastSuccessfulAt ? new Date(syncQuery.data.settings.lastSuccessfulAt).toLocaleString() : "Not yet"}</dd></div><div className="flex justify-between gap-4"><dt>Last attempt</dt><dd>{syncQuery.data?.settings?.lastAttemptAt ? new Date(syncQuery.data.settings.lastAttemptAt).toLocaleString() : "Not yet"}</dd></div></dl><Button className="mt-5 gap-2" disabled={runSync.isPending} onClick={() => runSync.mutate()}>{<RefreshCw className={`h-4 w-4 ${runSync.isPending ? "animate-spin" : ""}`}/>}Run sync now</Button></div><div className="rounded-xl border bg-card text-card-foreground overflow-hidden"><div className="p-4 border-b font-semibold">Recent runs</div><div className="divide-y">{syncQuery.data?.runs.map(run => <div key={run.id} className="p-4 flex justify-between gap-4 text-sm"><div><Badge variant={run.status === "success" ? "default" : run.status === "failed" ? "destructive" : "secondary"}>{run.status}</Badge><p className="mt-2 text-muted-foreground">Found {run.programsFound}, created {run.programsCreated}, updated {run.programsUpdated}</p>{run.errorMessage && <p className="text-red-600 mt-1">{run.errorMessage}</p>}</div><time className="text-xs text-muted-foreground whitespace-nowrap">{new Date(run.startedAt).toLocaleString()}</time></div>)}</div></div></section>}

    <CreateAccountDialog open={createOpen} onOpenChange={setCreateOpen} cases={casesQuery.data || []} onCreated={data => { setCreateOpen(false); setCredentials(data); accountsQuery.refetch(); }}/>
    <CredentialsDialog credentials={credentials} onClose={() => setCredentials(null)}/>
    <MessageDialog application={messageApplication} onClose={() => setMessageApplication(null)} messages={messagesQuery.data || []} reply={reply} setReply={setReply} visibility={replyVisibility} setVisibility={setReplyVisibility} pending={sendReply.isPending} send={() => messageApplication && sendReply.mutate({ applicationPublicId: messageApplication.publicId, body: reply.trim(), visibility: replyVisibility })}/>
    <DocumentsDialog application={documentApplication} onClose={() => setDocumentApplication(null)}/>
    <ProgramDialog program={programEdit} onClose={() => setProgramEdit(null)} onSave={values => saveProgram.mutate(values)} pending={saveProgram.isPending}/>
    <ProviderDialog provider={providerEdit} onClose={() => setProviderEdit(null)} onSave={values => saveProvider.mutate(values)} pending={saveProvider.isPending}/>
  </div>;
}

function PanelMessage({ children }: { children: React.ReactNode }) { return <div className="rounded-xl border border-dashed p-10 text-center text-muted-foreground">{children}</div>; }

function MessageDialog({ application, onClose, messages, reply, setReply, visibility, setVisibility, pending, send }: any) {
  return <Dialog open={Boolean(application)} onOpenChange={open => { if (!open) onClose(); }}><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>Secure client conversation</DialogTitle><DialogDescription>{application?.label}</DialogDescription></DialogHeader><div className="max-h-[45vh] overflow-y-auto space-y-3 p-1">{messages.map((message: any) => <div key={message.publicId} className={`max-w-[85%] rounded-xl px-3 py-2 text-sm ${message.senderType === "client" ? "bg-muted mr-auto" : message.visibility === "internal" ? "bg-amber-50 text-amber-900 ml-auto" : "bg-[#dff4f7] text-[#123c46] ml-auto"}`}><p>{message.body}</p><p className="text-[10px] opacity-60 mt-1">{message.visibility === "internal" ? "Internal note · " : ""}{new Date(message.createdAt).toLocaleString()}</p></div>)}</div><Textarea value={reply} onChange={event => setReply(event.target.value)} placeholder="Write a secure reply…" maxLength={5000}/><div className="flex justify-between gap-3"><select className="h-10 rounded-md border bg-background px-3 text-sm" value={visibility} onChange={event => setVisibility(event.target.value)}><option value="client">Visible to client</option><option value="internal">Internal note</option></select><Button disabled={!reply.trim() || pending} onClick={send}>Send</Button></div></DialogContent></Dialog>;
}

function DocumentsDialog({ application, onClose }: { application: ApplicationRef | null; onClose: () => void }) {
  const query = trpc.clientPortalAdmin.listDocuments.useQuery({ applicationPublicId: application?.publicId || EMPTY_UUID }, { enabled: Boolean(application) });
  const access = trpc.clientPortalAdmin.getDocumentAccess.useMutation({ onSuccess: data => window.open(data.url, "_blank", "noopener,noreferrer"), onError: error => toast.error(error.message) });
  const review = trpc.clientPortalAdmin.reviewDocument.useMutation({ onSuccess: () => { query.refetch(); toast.success("Document status updated"); }, onError: error => toast.error(error.message) });
  return <Dialog open={Boolean(application)} onOpenChange={open => { if (!open) onClose(); }}><DialogContent className="max-w-3xl"><DialogHeader><DialogTitle>Client documents</DialogTitle><DialogDescription>{application?.label} · Files are append-only and every access is audited.</DialogDescription></DialogHeader><div className="max-h-[60vh] overflow-y-auto space-y-3">{query.isLoading && <PanelMessage>Loading documents…</PanelMessage>}{!query.isLoading && !query.data?.length && <PanelMessage>No submitted documents for this application.</PanelMessage>}{query.data?.map(document => <article key={document.publicId} className="rounded-xl border p-4"><div className="flex flex-col md:flex-row md:items-start justify-between gap-3"><div className="min-w-0"><h3 className="font-semibold truncate">{document.fileName}</h3><p className="text-sm text-muted-foreground">{document.documentType} · {(document.fileSize / 1024 / 1024).toFixed(1)} MB · {new Date(document.createdAt).toLocaleString()}</p>{document.clientComment && <p className="mt-2 text-sm rounded-md bg-muted p-2">{document.clientComment}</p>}</div><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" className="gap-1" onClick={() => access.mutate({ publicId: document.publicId })}><ExternalLink className="h-4 w-4"/>Open</Button><Button size="sm" variant="outline" onClick={() => review.mutate({ publicId: document.publicId, reviewStatus: document.reviewStatus, visibleToClient: !document.visibleToClient, clientComment: document.clientComment })}>{document.visibleToClient ? "Hide" : "Show"}</Button></div></div><div className="flex items-center gap-3 mt-3"><label className="text-xs font-medium" htmlFor={`status-${document.publicId}`}>Review status</label><select id={`status-${document.publicId}`} className="h-9 rounded-md border bg-background px-3 text-sm" value={document.reviewStatus} onChange={event => review.mutate({ publicId: document.publicId, reviewStatus: event.target.value as any, visibleToClient: document.visibleToClient, clientComment: document.clientComment })}><option value="submitted">Submitted</option><option value="under_review">Under review</option><option value="accepted">Accepted</option><option value="replacement_required">Replacement required</option></select><Badge variant={document.visibleToClient ? "default" : "secondary"}>{document.visibleToClient ? "Client visible" : "Hidden"}</Badge></div></article>)}</div></DialogContent></Dialog>;
}

function CreateAccountDialog({ open, onOpenChange, cases, onCreated }: { open: boolean; onOpenChange: (open: boolean) => void; cases: any[]; onCreated: (data: any) => void }) {
  const [selectedCases, setSelectedCases] = useState<number[]>([]);
  const [primaryCaseId, setPrimaryCaseId] = useState<number | null>(null);
  const [username, setUsername] = useState("");
  const [email, setEmail] = useState("");
  const [mobile, setMobile] = useState("");
  const mutation = trpc.clientPortalAdmin.createAccount.useMutation({ onSuccess: onCreated, onError: error => toast.error(error.message) });
  const selected = useMemo(() => new Set(selectedCases), [selectedCases]);
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>Create client access</DialogTitle><DialogDescription>Step 1: create the client credentials. Step 2: select the CRM Client Documentation folder(s) that this account can open. Credentials will be shown once.</DialogDescription></DialogHeader><div className="grid sm:grid-cols-2 gap-3"><Input placeholder="Username" value={username} onChange={event => setUsername(event.target.value)}/><Input type="email" placeholder="Client email" value={email} onChange={event => setEmail(event.target.value)}/><Input placeholder="Mobile" value={mobile} onChange={event => setMobile(event.target.value)}/><select className="h-10 rounded-md border bg-background px-3 text-sm" value={primaryCaseId || ""} onChange={event => setPrimaryCaseId(Number(event.target.value))}><option value="">Primary documentation folder</option>{cases.filter(item => selected.has(item.id)).map(item => <option key={item.id} value={item.id}>{item.clientName} · {item.clientCode}</option>)}</select></div><div className="border rounded-xl max-h-56 overflow-y-auto divide-y"><div className="sticky top-0 bg-muted p-2 text-xs font-semibold">Select Client Documentation folder(s)</div>{cases.map(item => <label key={item.id} className="flex items-start gap-3 p-3 cursor-pointer hover:bg-muted/50"><input type="checkbox" className="mt-1" checked={selected.has(item.id)} onChange={event => { const next = event.target.checked ? [...selectedCases, item.id] : selectedCases.filter(id => id !== item.id); setSelectedCases(next); if (event.target.checked && !primaryCaseId) setPrimaryCaseId(item.id); if (!event.target.checked && primaryCaseId === item.id) setPrimaryCaseId(next[0] || null); }}/><span><span className="font-medium text-sm">{item.clientName}</span><span className="block text-xs text-muted-foreground">{item.clientCode} · {item.applicationType} · {item.stage}</span></span></label>)}</div><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button disabled={!username || !email || !primaryCaseId || !selectedCases.length || mutation.isPending} onClick={() => mutation.mutate({ caseIds: selectedCases, primaryCaseId: primaryCaseId!, username, email, mobile: mobile || undefined, locale: "en" })}>{mutation.isPending ? "Creating…" : "Create secure access"}</Button></DialogFooter></DialogContent></Dialog>;
}

function CredentialsDialog({ credentials, onClose }: { credentials: { username: string; email: string; temporaryPassword: string } | null; onClose: () => void }) {
  const copy = async () => { if (!credentials) return; await navigator.clipboard.writeText(`Username: ${credentials.username}\nEmail: ${credentials.email}\nTemporary password: ${credentials.temporaryPassword}`); toast.success("Credentials copied"); };
  return <Dialog open={Boolean(credentials)} onOpenChange={open => { if (!open) onClose(); }}><DialogContent><DialogHeader><DialogTitle>Client credentials</DialogTitle><DialogDescription>Share these securely. The client must change the temporary password after first login.</DialogDescription></DialogHeader>{credentials && <div className="rounded-xl bg-muted p-4 font-mono text-sm space-y-2"><p>Username: {credentials.username}</p><p>Email: {credentials.email}</p><p className="break-all">Temporary password: {credentials.temporaryPassword}</p></div>}<DialogFooter><Button variant="outline" onClick={copy}>Copy</Button><Button onClick={onClose}>I stored them securely</Button></DialogFooter></DialogContent></Dialog>;
}

function ProgramDialog({ program, onClose, onSave, pending }: { program: any; onClose: () => void; onSave: (values: any) => void; pending: boolean }) {
  const [draft, setDraft] = useState<any>(null);
  const value = draft?.publicId === program?.publicId ? draft : program;
  if (!program || !value) return null;
  const change = (key: string, next: any) => setDraft({ ...value, [key]: next });
  const save = (clearOverride: boolean) => onSave({ publicId: value.publicId, nameEn: value.nameEn, nameAr: value.nameAr || null, summaryEn: value.summaryEn || null, summaryAr: value.summaryAr || null, imageUrl: value.imageUrl || null, displayOrder: value.displayOrder, isActive: value.isActive, clearOverride });
  return <Dialog open onOpenChange={open => { if (!open) onClose(); }}><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>Edit program</DialogTitle><DialogDescription>Saving creates a manual override. Clear it to resume website updates.</DialogDescription></DialogHeader><Input value={value.nameEn} onChange={event => change("nameEn", event.target.value)} placeholder="English name"/><Input dir="rtl" value={value.nameAr || ""} onChange={event => change("nameAr", event.target.value)} placeholder="الاسم العربي"/><Textarea value={value.summaryEn || ""} onChange={event => change("summaryEn", event.target.value)} placeholder="English summary"/><Textarea dir="rtl" value={value.summaryAr || ""} onChange={event => change("summaryAr", event.target.value)} placeholder="الملخص العربي"/><Input value={value.imageUrl || ""} onChange={event => change("imageUrl", event.target.value)} placeholder="Image URL"/><div className="flex gap-4"><label className="text-sm"><input type="checkbox" checked={value.isActive} onChange={event => change("isActive", event.target.checked)} className="mr-2"/>Visible in app</label><Input type="number" value={value.displayOrder} onChange={event => change("displayOrder", Number(event.target.value))} className="w-28"/></div><DialogFooter><Button variant="outline" onClick={() => save(true)}>Resume website sync</Button><Button disabled={pending} onClick={() => save(false)}>Save override</Button></DialogFooter></DialogContent></Dialog>;
}

function ProviderDialog({ provider, onClose, onSave, pending }: { provider: any; onClose: () => void; onSave: (values: any) => void; pending: boolean }) {
  const [draft, setDraft] = useState<any>(null);
  const value = draft?.publicId === provider?.publicId || (!provider?.publicId && draft) ? draft : provider;
  if (!provider || !value) return null;
  const change = (key: string, next: any) => setDraft({ ...value, [key]: next });
  const save = () => onSave({ publicId: value.publicId, providerType: value.providerType, name: value.name, country: value.country, city: value.city || null, logoUrl: value.logoUrl || null, description: value.description || null, services: value.services || [], price: value.price || null, currency: value.currency || null, phone: value.phone || null, whatsapp: value.whatsapp || null, email: value.email || null, website: value.website || null, languages: value.languages || [], availability: value.availability || null, displayOrder: value.displayOrder || 0, isActive: value.isActive });
  return <Dialog open onOpenChange={open => { if (!open) onClose(); }}><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>{value.publicId ? "Edit" : "Add"} service provider</DialogTitle></DialogHeader><div className="grid sm:grid-cols-2 gap-3"><select className="h-10 rounded-md border bg-background px-3 text-sm" value={value.providerType} onChange={event => change("providerType", event.target.value)}><option value="lawyer">Lawyer</option><option value="accountant">Accountant</option><option value="service_facilitator">Service facilitator</option></select><Input value={value.name || ""} onChange={event => change("name", event.target.value)} placeholder="Provider name"/><Input value={value.country || ""} onChange={event => change("country", event.target.value)} placeholder="Country"/><Input value={value.city || ""} onChange={event => change("city", event.target.value)} placeholder="City"/><Input value={value.email || ""} onChange={event => change("email", event.target.value)} placeholder="Email"/><Input value={value.phone || ""} onChange={event => change("phone", event.target.value)} placeholder="Phone"/><Input value={value.whatsapp || ""} onChange={event => change("whatsapp", event.target.value)} placeholder="WhatsApp"/><Input value={value.website || ""} onChange={event => change("website", event.target.value)} placeholder="Website URL"/><Input value={value.price || ""} onChange={event => change("price", event.target.value)} placeholder="Price"/><Input value={value.currency || ""} onChange={event => change("currency", event.target.value)} placeholder="Currency"/></div><Textarea value={value.description || ""} onChange={event => change("description", event.target.value)} placeholder="Description"/><Input value={(value.services || []).join(", ")} onChange={event => change("services", event.target.value.split(",").map((item: string) => item.trim()).filter(Boolean))} placeholder="Services, comma separated"/><Input value={(value.languages || []).join(", ")} onChange={event => change("languages", event.target.value.split(",").map((item: string) => item.trim()).filter(Boolean))} placeholder="Languages, comma separated"/><div className="flex gap-4"><label className="text-sm"><input type="checkbox" checked={value.isActive} onChange={event => change("isActive", event.target.checked)} className="mr-2"/>Visible in app</label><Input type="number" value={value.displayOrder || 0} onChange={event => change("displayOrder", Number(event.target.value))} className="w-28"/></div><DialogFooter><Button variant="outline" onClick={onClose}>Cancel</Button><Button disabled={pending || !value.name || !value.country} onClick={save}>Save provider</Button></DialogFooter></DialogContent></Dialog>;
}
