import { useMemo, useState } from "react";
import { useLocation } from "wouter";
import {
  AlertTriangle, BadgeCheck, Ban, CheckCircle2, ChevronDown, ClipboardCheck,
  Eye, FileClock, FilePenLine, LockKeyhole, PauseCircle, Plus, RefreshCw,
  Send, ShieldAlert, ShieldCheck, SquareCheckBig, StopCircle, XCircle,
} from "lucide-react";
import { trpc } from "@/lib/trpc";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";

const CONTENT_TYPES = [
  ["static_post", "Static post"], ["carousel", "Carousel"], ["reel", "Reel"], ["lead_ad", "Lead ad"], ["landing_page", "Landing page"],
] as const;
const PLATFORMS = ["instagram", "facebook", "tiktok", "linkedin", "youtube", "whatsapp", "web"] as const;
const QA_CHECKS = [
  ["factual_claims", "Factual claims and source links"],
  ["brand_tone", "Premium ELEVAY tone and message hierarchy"],
  ["arabic_language", "Arabic language and programme terminology"],
  ["visual_identity", "Official logo, palette, typography and luxury direction"],
  ["safe_areas", "Platform safe areas and readability"],
  ["accessibility", "Captions, alt text and contrast"],
  ["cta_and_destination", "CTA and destination consistency"],
  ["asset_provenance", "Asset provenance and licensing"],
  ["no_guarantees", "No immigration, financial or timing guarantees"],
  ["preview_equivalence", "Final preview equivalence"],
] as const;

type PacketStatus = "draft" | "in_review" | "changes_requested" | "qa_passed" | "approval_ready" | "approved" | "rejected" | "stopped" | "superseded" | string;
type QaKey = typeof QA_CHECKS[number][0];

function formatDate(value?: number | null) {
  return value ? new Date(value).toLocaleString() : "Not set";
}

function StatusBadge({ status }: { status: PacketStatus }) {
  const styles: Record<string, string> = {
    draft: "border-slate-400/30 bg-slate-400/10 text-slate-200",
    in_review: "border-sky-400/30 bg-sky-400/10 text-sky-100",
    changes_requested: "border-amber-400/30 bg-amber-400/10 text-amber-100",
    qa_passed: "border-emerald-400/30 bg-emerald-400/10 text-emerald-100",
    approval_ready: "border-violet-400/30 bg-violet-400/10 text-violet-100",
    approved: "border-emerald-400/40 bg-emerald-400/15 text-emerald-100",
    rejected: "border-rose-400/30 bg-rose-400/10 text-rose-100",
    stopped: "border-rose-400/30 bg-rose-400/10 text-rose-100",
    superseded: "border-slate-400/30 bg-slate-400/10 text-slate-300",
  };
  return <Badge variant="outline" className={styles[status] ?? styles.draft}>{status.replaceAll("_", " ")}</Badge>;
}

function safeJson(value: string) {
  if (!value.trim()) return {};
  try {
    const parsed = JSON.parse(value);
    if (!parsed || Array.isArray(parsed) || typeof parsed !== "object") throw new Error("not object");
    return parsed as Record<string, unknown>;
  } catch {
    throw new Error("Packet details JSON must be a valid JSON object.");
  }
}

export default function ContentStudio() {
  const [, navigate] = useLocation();
  const utils = trpc.useUtils();
  const { data: access, isLoading: accessLoading } = trpc.marketingSystem.access.useQuery();
  const canView = access?.capabilities.includes("view_content_studio") === true;
  const canCreate = access?.capabilities.includes("create_content_packets") === true;
  const canReview = access?.capabilities.includes("review_content_packets") === true;
  const canQa = access?.capabilities.includes("run_content_qa") === true;
  const canStop = access?.capabilities.includes("stop_content_packets") === true;
  const isOwner = ["owner", "marketing_system_admin"].includes(access?.role ?? "");
  const { data: config, isLoading: configLoading } = trpc.marketingSystem.getContentStudioConfiguration.useQuery(undefined, { enabled: canView });
  const { data: contentData, isLoading: packetsLoading } = trpc.marketingSystem.getContentPackets.useQuery(undefined, { enabled: canView });

  const [form, setForm] = useState({
    workOrderId: "", contentType: "static_post", title: "", programKey: "", platforms: ["instagram"] as string[],
    funnelStage: "awareness", audience: "", objective: "", arabicCopy: "", englishCopy: "", caption: "", cta: "",
    landingDestination: "", scheduledFor: "", visualBrief: "", payloadJson: "{}", previewUrl: "", previewHash: "",
    exceptionalClaim: false, changeSummary: "Initial manual packet.",
  });
  const [selectedClaims, setSelectedClaims] = useState<number[]>([]);
  const [revisionSourceId, setRevisionSourceId] = useState<number | null>(null);
  const [qaPasses, setQaPasses] = useState<Record<string, boolean>>(() => Object.fromEntries(QA_CHECKS.map(([key]) => [key, true])));
  const [qaNotes, setQaNotes] = useState<Record<string, string>>(() => Object.fromEntries(QA_CHECKS.map(([, label]) => [label, "Checked manually against the final packet."])));
  const [qaFeedback, setQaFeedback] = useState<Record<number, string>>({});
  const [reviewNotes, setReviewNotes] = useState<Record<number, string>>({});
  const [stopNotes, setStopNotes] = useState<Record<number, string>>({});
  const [selectedBatchIds, setSelectedBatchIds] = useState<number[]>([]);
  const [batchNote, setBatchNote] = useState("");
  const [batchConfirmed, setBatchConfirmed] = useState(false);

  const packets = contentData?.packets ?? [];
  const approvedOrders = config?.workOrders ?? [];
  const selectedOrder = approvedOrders.find(order => String(order.id) === form.workOrderId) ?? null;
  const availableClaims = useMemo(() => (config?.claims ?? []).filter(claim =>
    (!form.programKey || claim.programKey === form.programKey) && (!selectedOrder || selectedOrder.claimIds.includes(claim.id)),
  ), [config?.claims, form.programKey, selectedOrder]);
  const approvalReady = packets.filter(packet => packet.status === "approval_ready");

  const invalidate = async () => {
    await Promise.all([
      utils.marketingSystem.getContentPackets.invalidate(),
      utils.marketingSystem.getContentStudioConfiguration.invalidate(),
    ]);
  };
  const resetForm = () => {
    setForm({ workOrderId: "", contentType: "static_post", title: "", programKey: "", platforms: ["instagram"], funnelStage: "awareness", audience: "", objective: "", arabicCopy: "", englishCopy: "", caption: "", cta: "", landingDestination: "", scheduledFor: "", visualBrief: "", payloadJson: "{}", previewUrl: "", previewHash: "", exceptionalClaim: false, changeSummary: "Initial manual packet." });
    setSelectedClaims([]);
    setRevisionSourceId(null);
  };
  const input = () => ({
    workOrderId: Number(form.workOrderId), contentType: form.contentType as "static_post" | "carousel" | "reel" | "lead_ad" | "landing_page",
    title: form.title, programKey: form.programKey, platforms: form.platforms as Array<"instagram" | "facebook" | "tiktok" | "linkedin" | "youtube" | "whatsapp" | "web">,
    funnelStage: form.funnelStage, audience: form.audience, objective: form.objective, arabicCopy: form.arabicCopy,
    ...(form.englishCopy.trim() ? { englishCopy: form.englishCopy } : {}), ...(form.caption.trim() ? { caption: form.caption } : {}),
    cta: form.cta, ...(form.landingDestination.trim() ? { landingDestination: form.landingDestination } : {}),
    ...(form.scheduledFor ? { scheduledFor: new Date(form.scheduledFor).getTime() } : {}), claimIds: selectedClaims,
    ...(form.visualBrief.trim() ? { visualBrief: form.visualBrief } : {}), payload: safeJson(form.payloadJson),
    ...(form.previewUrl.trim() ? { previewUrl: form.previewUrl } : {}), ...(form.previewHash.trim() ? { previewHash: form.previewHash } : {}),
    exceptionalClaim: form.exceptionalClaim, changeSummary: form.changeSummary,
  });

  const create = trpc.marketingSystem.createContentPacket.useMutation({ onSuccess: async () => { await invalidate(); resetForm(); toast.success("Manual content packet saved. No model, rendering, publishing, campaign, or paid action was triggered."); }, onError: error => toast.error(error.message) });
  const revise = trpc.marketingSystem.reviseContentPacket.useMutation({ onSuccess: async () => { await invalidate(); resetForm(); toast.success("A new immutable packet revision was created; the prior revision remains in lineage."); }, onError: error => toast.error(error.message) });
  const submit = trpc.marketingSystem.submitContentPacketForReview.useMutation({ onSuccess: async () => { await invalidate(); toast.success("Packet sent to internal review."); }, onError: error => toast.error(error.message) });
  const qa = trpc.marketingSystem.recordContentQa.useMutation({ onSuccess: async result => { await invalidate(); toast.success(result.status === "qa_passed" ? "All QA checks passed." : "QA feedback returned the packet for changes."); }, onError: error => toast.error(error.message) });
  const ready = trpc.marketingSystem.makeContentApprovalReady.useMutation({ onSuccess: async () => { await invalidate(); toast.success("Final packet is now in Mahmoud’s Approval Inbox."); }, onError: error => toast.error(error.message) });
  const requestChanges = trpc.marketingSystem.requestContentChanges.useMutation({ onSuccess: async () => { await invalidate(); toast.success("Structured change request retained in packet lineage."); }, onError: error => toast.error(error.message) });
  const approve = trpc.marketingSystem.approveContentPacket.useMutation({ onSuccess: async () => { await invalidate(); toast.success("Owner approval recorded. This did not publish, schedule, activate a campaign, or spend money."); }, onError: error => toast.error(error.message) });
  const reject = trpc.marketingSystem.rejectContentPacket.useMutation({ onSuccess: async () => { await invalidate(); toast.success("Owner rejection recorded with retained feedback."); }, onError: error => toast.error(error.message) });
  const stop = trpc.marketingSystem.stopContentPacket.useMutation({ onSuccess: async () => { await invalidate(); toast.success("Packet stopped. No external action was sent."); }, onError: error => toast.error(error.message) });
  const batchApprove = trpc.marketingSystem.approveContentBatch.useMutation({ onSuccess: async result => { await invalidate(); setSelectedBatchIds([]); setBatchNote(""); setBatchConfirmed(false); toast.success(`${result.approvedPacketIds.length} fully reviewed packets approved. No publishing action was sent.`); }, onError: error => toast.error(error.message) });

  const togglePlatform = (platform: string) => setForm(current => ({ ...current, platforms: current.platforms.includes(platform) ? current.platforms.filter(item => item !== platform) : [...current.platforms, platform] }));
  const prepareRevision = (packet: typeof packets[number]) => {
    setRevisionSourceId(packet.id);
    setForm({ workOrderId: String(packet.workOrderId), contentType: packet.contentType, title: packet.title, programKey: packet.programKey, platforms: packet.platforms, funnelStage: packet.funnelStage, audience: packet.audience, objective: packet.objective, arabicCopy: packet.arabicCopy, englishCopy: packet.englishCopy ?? "", caption: packet.caption ?? "", cta: packet.cta, landingDestination: packet.landingDestination ?? "", scheduledFor: packet.scheduledFor ? new Date(packet.scheduledFor).toISOString().slice(0, 16) : "", visualBrief: packet.visualBrief ?? "", payloadJson: JSON.stringify(packet.payload, null, 2), previewUrl: packet.previewUrl ?? "", previewHash: packet.previewHash ?? "", exceptionalClaim: packet.exceptionalClaim, changeSummary: `Revision of v${packet.versionNumber}: ` });
    setSelectedClaims(packet.claimIds);
    window.scrollTo({ top: 0, behavior: "smooth" });
  };
  const submitForm = () => {
    try {
      const body = input();
      if (!body.workOrderId || !body.programKey || body.platforms.length === 0 || body.claimIds.length === 0) return toast.error("Select an approved work order, programme, platform, and approved claim(s).");
      if (revisionSourceId) revise.mutate({ ...body, previousPacketId: revisionSourceId, changeSummary: form.changeSummary });
      else create.mutate(body);
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Packet details are invalid.");
    }
  };
  const runQa = (packetId: number) => qa.mutate({ packetId, results: QA_CHECKS.map(([check, label]) => ({ check, passed: qaPasses[check] !== false, note: qaNotes[label] || "Manual QA result." })), feedback: qaFeedback[packetId] || undefined });

  if (accessLoading || (canView && (configLoading || packetsLoading))) return <div className="flex min-h-[65vh] items-center justify-center"><RefreshCw className="h-7 w-7 animate-spin text-[#5BA3B8]" /></div>;
  if (!canView) return <div className="mx-auto flex min-h-[65vh] max-w-xl flex-col items-center justify-center px-6 text-center"><LockKeyhole className="mb-4 h-12 w-12 text-amber-300" /><h1 className="text-2xl font-bold text-white">Content Studio access is controlled</h1><p className="mt-3 text-sm leading-6 text-slate-400">Ask Mahmoud to assign a Marketing System role. This workspace does not grant provider, publishing, campaign, or spending access.</p></div>;

  return <div className="min-h-full bg-[#0c1320] px-4 py-6 text-white md:px-8"><div className="mx-auto max-w-7xl space-y-6">
    <section className="relative overflow-hidden rounded-3xl border border-[#5BA3B8]/25 bg-[radial-gradient(circle_at_15%_0%,rgba(91,163,184,.22),transparent_36%),linear-gradient(115deg,#15263d,#0d1524_52%,#111827)] p-6 md:p-8">
      <div className="absolute right-0 top-0 h-36 w-36 rounded-full bg-[#C9A84C]/10 blur-3xl" />
      <div className="relative flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div className="max-w-3xl"><div className="mb-3 flex items-center gap-2 text-[#a9d6e3]"><FilePenLine className="h-4 w-4" /><span className="text-xs font-bold uppercase tracking-[.18em]">Agentic Marketing System · Phase 4</span></div><h1 className="text-3xl font-semibold tracking-tight md:text-4xl">Content Studio & Approval Inbox</h1><p className="mt-3 text-sm leading-6 text-slate-300">Versioned, evidence-linked content packets and Mahmoud’s final approval decisions. Every action stays inside ELEVAY: this phase has no model call, media render, publication, schedule, campaign activation, CAPI change, client message, or spend action.</p></div><div className="grid grid-cols-3 gap-3 text-sm"><div className="rounded-2xl border border-white/10 bg-black/20 px-4 py-3"><p className="text-slate-400">Packets</p><p className="mt-1 font-semibold">{packets.length}</p></div><div className="rounded-2xl border border-white/10 bg-black/20 px-4 py-3"><p className="text-slate-400">Approval inbox</p><p className="mt-1 font-semibold text-violet-200">{approvalReady.length}</p></div><div className="rounded-2xl border border-white/10 bg-black/20 px-4 py-3"><p className="text-slate-400">Published</p><p className="mt-1 font-semibold text-emerald-200">0</p></div></div></div>
    </section>

    <Card className="border-amber-400/30 bg-amber-400/10 text-white"><CardContent className="flex gap-3 p-4"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-amber-200" /><div><p className="font-semibold text-amber-100">Manual content control only</p><p className="mt-1 text-sm leading-6 text-amber-100/75">{contentData?.policy}</p></div></CardContent></Card>

    {(config?.blockers ?? []).length > 0 && <Card className="border-rose-400/25 bg-rose-400/10 text-white"><CardContent className="flex gap-3 p-4"><ShieldAlert className="mt-0.5 h-5 w-5 shrink-0 text-rose-200" /><div><p className="font-semibold text-rose-100">Creation gates are not yet satisfied</p><ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-rose-100/80">{config?.blockers.map(blocker => <li key={blocker}>{blocker}</li>)}</ul><p className="mt-2 text-xs text-rose-100/70">You can still inspect the workspace, but a content packet cannot bypass its Brand Book, approved-work-order, or approved-claim gates.</p></div></CardContent></Card>}

    {canCreate && <Card className="border-[#5BA3B8]/25 bg-[#111b2c] text-white"><CardHeader><div className="flex flex-wrap items-start justify-between gap-3"><div><CardTitle className="flex items-center gap-2"><Plus className="h-5 w-5 text-[#8ad5e7]" />{revisionSourceId ? "Create controlled revision" : "Create manual content packet"}</CardTitle><CardDescription className="mt-1 text-slate-400">Enter a human-prepared packet only. Keep it free of client/Lead names, numbers, emails, passport details, and guarantees. Arabic is the required primary copy.</CardDescription></div>{revisionSourceId && <Button size="sm" variant="outline" onClick={resetForm} className="border-white/15 bg-transparent text-slate-300 hover:bg-white/5 hover:text-white">Cancel revision</Button>}</div></CardHeader><CardContent className="space-y-5">
      <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><div><Label>Approved source work order</Label><Select value={form.workOrderId} onValueChange={value => { const order = approvedOrders.find(item => String(item.id) === value); setForm(current => ({ ...current, workOrderId: value, programKey: order?.programKey ?? current.programKey })); setSelectedClaims([]); }}><SelectTrigger className="mt-1 border-white/10 bg-[#0c1320]"><SelectValue placeholder="Select approved work order" /></SelectTrigger><SelectContent>{approvedOrders.map(order => <SelectItem key={order.id} value={String(order.id)}>{order.workOrderKey} · {order.title}</SelectItem>)}</SelectContent></Select></div><div><Label>Content type</Label><Select value={form.contentType} onValueChange={value => setForm(current => ({ ...current, contentType: value }))}><SelectTrigger className="mt-1 border-white/10 bg-[#0c1320]"><SelectValue /></SelectTrigger><SelectContent>{CONTENT_TYPES.map(([value, label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></div><div><Label>Programme key</Label><Input value={form.programKey} onChange={event => { setForm(current => ({ ...current, programKey: event.target.value.toLowerCase().replace(/[^a-z0-9_]/g, "") })); setSelectedClaims([]); }} className="mt-1 border-white/10 bg-[#0c1320] text-white" placeholder="spain_digital_nomad_residency" /></div><div><Label>Funnel stage</Label><Input value={form.funnelStage} onChange={event => setForm(current => ({ ...current, funnelStage: event.target.value }))} className="mt-1 border-white/10 bg-[#0c1320] text-white" placeholder="awareness" /></div></div>
      <div className="grid gap-3 md:grid-cols-2"><div><Label>Packet title</Label><Input value={form.title} onChange={event => setForm(current => ({ ...current, title: event.target.value }))} className="mt-1 border-white/10 bg-[#0c1320] text-white" placeholder="Programme-specific educational post" /></div><div><Label>Audience</Label><Input value={form.audience} onChange={event => setForm(current => ({ ...current, audience: event.target.value }))} className="mt-1 border-white/10 bg-[#0c1320] text-white" placeholder="Target audience, without personal data" /></div><div><Label>Objective</Label><Input value={form.objective} onChange={event => setForm(current => ({ ...current, objective: event.target.value }))} className="mt-1 border-white/10 bg-[#0c1320] text-white" placeholder="Measured internal marketing objective" /></div><div><Label>CTA</Label><Input value={form.cta} onChange={event => setForm(current => ({ ...current, cta: event.target.value }))} className="mt-1 border-white/10 bg-[#0c1320] text-white" placeholder="Book a consultation / Learn more" /></div></div>
      <div><Label>Platforms</Label><div className="mt-2 flex flex-wrap gap-2">{PLATFORMS.map(platform => <label key={platform} className="flex cursor-pointer items-center gap-2 rounded-full border border-white/10 bg-white/5 px-3 py-1.5 text-xs text-slate-300"><input type="checkbox" checked={form.platforms.includes(platform)} onChange={() => togglePlatform(platform)} className="accent-[#5BA3B8]" />{platform}</label>)}</div></div>
      <div className="rounded-2xl border border-[#5BA3B8]/20 bg-[#0c1320] p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="font-medium">Approved claim references</p><p className="mt-1 text-xs text-slate-400">Only tracked, owner-approved claims already attached to the selected work order can be used.</p></div><Badge variant="outline" className="border-[#5BA3B8]/30 text-[#a9d6e3]">{selectedClaims.length} selected</Badge></div>{availableClaims.length === 0 ? <p className="mt-3 text-sm text-amber-200">Select an eligible work order and programme. No claim can be invented or entered free-form.</p> : <div className="mt-3 grid gap-2 lg:grid-cols-2">{availableClaims.map(claim => <label key={claim.id} className="flex cursor-pointer gap-3 rounded-xl border border-white/10 bg-white/5 p-3 text-sm"><input type="checkbox" checked={selectedClaims.includes(claim.id)} onChange={event => setSelectedClaims(current => event.target.checked ? [...current, claim.id] : current.filter(id => id !== claim.id))} className="mt-1 h-4 w-4 accent-[#5BA3B8]" /><span><span className="font-medium text-slate-200">{claim.programKey.replaceAll("_", " ")} · {claim.claimType.replaceAll("_", " ")}</span><span className="mt-1 block line-clamp-2 text-xs leading-5 text-slate-400">{claim.claimText}</span></span></label>)}</div>}</div>
      <div className="grid gap-4 lg:grid-cols-2"><div><Label>Arabic primary copy</Label><Textarea dir="rtl" value={form.arabicCopy} onChange={event => setForm(current => ({ ...current, arabicCopy: event.target.value }))} className="mt-1 min-h-44 border-white/10 bg-[#0c1320] text-white" placeholder="اكتب النص العربي المعتمد هنا..." /></div><div className="space-y-3"><div><Label>Optional English copy</Label><Textarea value={form.englishCopy} onChange={event => setForm(current => ({ ...current, englishCopy: event.target.value }))} className="mt-1 min-h-20 border-white/10 bg-[#0c1320] text-white" /></div><div><Label>Caption</Label><Textarea value={form.caption} onChange={event => setForm(current => ({ ...current, caption: event.target.value }))} className="mt-1 min-h-20 border-white/10 bg-[#0c1320] text-white" /></div></div></div>
      <div className="grid gap-3 md:grid-cols-2"><div><Label>Visual brief</Label><Textarea value={form.visualBrief} onChange={event => setForm(current => ({ ...current, visualBrief: event.target.value }))} className="mt-1 min-h-24 border-white/10 bg-[#0c1320] text-white" placeholder="Luxury, premium visual direction; official logo unchanged; no passport image or guarantees." /></div><div><Label>Structured packet details (JSON object)</Label><Textarea value={form.payloadJson} onChange={event => setForm(current => ({ ...current, payloadJson: event.target.value }))} className="mt-1 min-h-24 font-mono text-xs border-white/10 bg-[#0c1320] text-white" placeholder='{"hook":"...","hashtags":["..."]}' /></div></div>
      <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><div><Label>Final HTTPS preview URL <span className="text-slate-500">required before QA</span></Label><Input value={form.previewUrl} onChange={event => setForm(current => ({ ...current, previewUrl: event.target.value }))} className="mt-1 border-white/10 bg-[#0c1320] text-white" placeholder="https://..." /></div><div><Label>Preview SHA-256 <span className="text-slate-500">required before QA</span></Label><Input value={form.previewHash} onChange={event => setForm(current => ({ ...current, previewHash: event.target.value.toLowerCase() }))} className="mt-1 border-white/10 bg-[#0c1320] font-mono text-xs text-white" placeholder="64 hex characters" /></div><div><Label>Proposed date/time <span className="text-slate-500">record only</span></Label><Input type="datetime-local" value={form.scheduledFor} onChange={event => setForm(current => ({ ...current, scheduledFor: event.target.value }))} className="mt-1 border-white/10 bg-[#0c1320] text-white" /></div><div><Label>Revision / change summary</Label><Input value={form.changeSummary} onChange={event => setForm(current => ({ ...current, changeSummary: event.target.value }))} className="mt-1 border-white/10 bg-[#0c1320] text-white" /></div></div>
      <label className="flex items-start gap-3 rounded-xl border border-amber-400/20 bg-amber-400/5 p-3 text-sm text-amber-50"><input type="checkbox" checked={form.exceptionalClaim} onChange={event => setForm(current => ({ ...current, exceptionalClaim: event.target.checked }))} className="mt-1 accent-amber-300" /><span><span className="font-semibold">Exceptional claim or policy-sensitive content</span><span className="mt-1 block text-xs text-amber-100/70">Mark it clearly. It cannot be included in bulk approval and requires an individual owner decision.</span></span></label>
      <Button disabled={create.isPending || revise.isPending || !config?.brandBook || approvedOrders.length === 0} onClick={submitForm} className="bg-[#5BA3B8] text-slate-950 hover:bg-[#82c8d9]"><FilePenLine className="mr-2 h-4 w-4" />{revisionSourceId ? "Create immutable revision" : "Save manual draft"}</Button>
    </CardContent></Card>}

    <section className="space-y-4"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-xl font-semibold">Approval Inbox</h2><p className="mt-1 text-sm text-slate-400">Only final-preview packets with every QA check passed appear here. Approval is recorded in ELEVAY and does not publish or schedule anything.</p></div><Badge variant="outline" className="border-violet-400/30 text-violet-100">{approvalReady.length} awaiting Mahmoud</Badge></div>
      {isOwner && approvalReady.filter(packet => !packet.exceptionalClaim).length >= 2 && <Card className="border-violet-400/25 bg-violet-400/10 text-white"><CardContent className="space-y-3 p-4"><div className="flex gap-3"><SquareCheckBig className="mt-0.5 h-5 w-5 shrink-0 text-violet-200" /><div><p className="font-semibold text-violet-100">Explicit weekly batch approval</p><p className="mt-1 text-sm text-violet-100/75">Select only routine packets you have individually opened and reviewed below. Exceptional claims remain individual-only.</p></div></div><div className="flex flex-wrap gap-2">{approvalReady.filter(packet => !packet.exceptionalClaim).map(packet => <label key={packet.id} className="flex cursor-pointer items-center gap-2 rounded-full border border-violet-200/20 bg-black/20 px-3 py-1.5 text-xs text-violet-50"><input type="checkbox" checked={selectedBatchIds.includes(packet.id)} onChange={event => setSelectedBatchIds(current => event.target.checked ? [...current, packet.id] : current.filter(id => id !== packet.id))} className="accent-violet-300" />#{packet.id} · {packet.title}</label>)}</div><Input value={batchNote} onChange={event => setBatchNote(event.target.value)} className="border-white/10 bg-[#0c1320] text-white" placeholder="Required owner note for this specific fully reviewed batch" /><label className="flex items-center gap-2 text-xs text-violet-100"><input type="checkbox" checked={batchConfirmed} onChange={event => setBatchConfirmed(event.target.checked)} className="accent-violet-300" />I opened and fully reviewed every selected final packet, preview, copy, claims, QA and planned destination.</label><Button disabled={batchApprove.isPending || selectedBatchIds.length < 2 || batchNote.trim().length < 4 || !batchConfirmed} onClick={() => batchApprove.mutate({ packetIds: selectedBatchIds, note: batchNote, confirmedFullyReviewed: true })} className="bg-violet-200 text-violet-950 hover:bg-violet-100"><BadgeCheck className="mr-2 h-4 w-4" />Approve selected batch</Button></CardContent></Card>}
      {approvalReady.length === 0 ? <Card className="border-dashed border-white/15 bg-[#111b2c] text-white"><CardContent className="py-12 text-center"><FileClock className="mx-auto h-8 w-8 text-slate-500" /><p className="mt-3 text-sm text-slate-400">No completed content packet awaits final approval.</p></CardContent></Card> : approvalReady.map(packet => <PacketCard key={packet.id} packet={packet} canCreate={canCreate} canReview={canReview} canQa={canQa} canStop={canStop} isOwner={isOwner} reviewNote={reviewNotes[packet.id] ?? ""} setReviewNote={value => setReviewNotes(current => ({ ...current, [packet.id]: value }))} stopNote={stopNotes[packet.id] ?? ""} setStopNote={value => setStopNotes(current => ({ ...current, [packet.id]: value }))} onRevision={() => prepareRevision(packet)} onSubmit={() => submit.mutate({ packetId: packet.id })} onQa={() => runQa(packet.id)} onReady={() => ready.mutate({ packetId: packet.id, note: reviewNotes[packet.id] || "QA passed and final packet checked." })} onChanges={() => requestChanges.mutate({ packetId: packet.id, note: reviewNotes[packet.id] || "Please revise this packet.", annotations: [] })} onApprove={() => approve.mutate({ packetId: packet.id, note: reviewNotes[packet.id] || "Explicit owner approval after final review.", annotations: [] })} onReject={() => reject.mutate({ packetId: packet.id, note: reviewNotes[packet.id] || "Owner rejection after final review.", annotations: [] })} onStop={() => stop.mutate({ packetId: packet.id, note: stopNotes[packet.id] || "Stop requested.", annotations: [] })} qaControls={{ qaPasses, setQaPasses, qaNotes, setQaNotes, qaFeedback: qaFeedback[packet.id] ?? "", setQaFeedback: value => setQaFeedback(current => ({ ...current, [packet.id]: value })) }} />)}
    </section>

    <section className="space-y-4"><div><h2 className="text-xl font-semibold">All packet lineage</h2><p className="mt-1 text-sm text-slate-400">Revisions, feedback, QA results, owner decisions and stop events are retained. A packet never becomes a live post here.</p></div>{packets.filter(packet => packet.status !== "approval_ready").length === 0 ? null : packets.filter(packet => packet.status !== "approval_ready").map(packet => <PacketCard key={packet.id} packet={packet} canCreate={canCreate} canReview={canReview} canQa={canQa} canStop={canStop} isOwner={isOwner} reviewNote={reviewNotes[packet.id] ?? ""} setReviewNote={value => setReviewNotes(current => ({ ...current, [packet.id]: value }))} stopNote={stopNotes[packet.id] ?? ""} setStopNote={value => setStopNotes(current => ({ ...current, [packet.id]: value }))} onRevision={() => prepareRevision(packet)} onSubmit={() => submit.mutate({ packetId: packet.id })} onQa={() => runQa(packet.id)} onReady={() => ready.mutate({ packetId: packet.id, note: reviewNotes[packet.id] || "QA passed and final packet checked." })} onChanges={() => requestChanges.mutate({ packetId: packet.id, note: reviewNotes[packet.id] || "Please revise this packet.", annotations: [] })} onApprove={() => approve.mutate({ packetId: packet.id, note: reviewNotes[packet.id] || "Explicit owner approval after final review.", annotations: [] })} onReject={() => reject.mutate({ packetId: packet.id, note: reviewNotes[packet.id] || "Owner rejection after final review.", annotations: [] })} onStop={() => stop.mutate({ packetId: packet.id, note: stopNotes[packet.id] || "Stop requested.", annotations: [] })} qaControls={{ qaPasses, setQaPasses, qaNotes, setQaNotes, qaFeedback: qaFeedback[packet.id] ?? "", setQaFeedback: value => setQaFeedback(current => ({ ...current, [packet.id]: value })) }} />)}</section>

    <div className="flex justify-end"><Button variant="ghost" onClick={() => navigate("/marketing")} className="text-slate-400 hover:bg-white/5 hover:text-white">Back to Marketing module</Button></div>
  </div></div>;
}

function PacketCard({ packet, canCreate, canReview, canQa, canStop, isOwner, reviewNote, setReviewNote, stopNote, setStopNote, onRevision, onSubmit, onQa, onReady, onChanges, onApprove, onReject, onStop, qaControls }: {
  packet: any; canCreate: boolean; canReview: boolean; canQa: boolean; canStop: boolean; isOwner: boolean; reviewNote: string; setReviewNote: (value: string) => void; stopNote: string; setStopNote: (value: string) => void; onRevision: () => void; onSubmit: () => void; onQa: () => void; onReady: () => void; onChanges: () => void; onApprove: () => void; onReject: () => void; onStop: () => void;
  qaControls: { qaPasses: Record<string, boolean>; setQaPasses: React.Dispatch<React.SetStateAction<Record<string, boolean>>>; qaNotes: Record<string, string>; setQaNotes: React.Dispatch<React.SetStateAction<Record<string, string>>>; qaFeedback: string; setQaFeedback: (value: string) => void; };
}) {
  const qaPassed = packet.qaResults.filter((result: { passed: boolean }) => result.passed).length;
  return <Card className="border-white/10 bg-[#111b2c] text-white"><CardHeader className="pb-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><div className="mb-2 flex flex-wrap items-center gap-2"><StatusBadge status={packet.status} /><Badge variant="outline" className="border-white/15 text-slate-300">{packet.contentType.replaceAll("_", " ")}</Badge><Badge variant="outline" className="border-[#5BA3B8]/30 text-[#a9d6e3]">{packet.programKey.replaceAll("_", " ")}</Badge>{packet.exceptionalClaim && <Badge variant="outline" className="border-amber-400/30 text-amber-100">Individual owner decision required</Badge>}</div><CardTitle className="text-lg">{packet.title}</CardTitle><CardDescription className="mt-2 max-w-3xl text-slate-400">{packet.objective}</CardDescription></div><div className="text-left text-xs text-slate-400 lg:text-right"><p>{packet.rootPacketKey} · v{packet.versionNumber}</p><p className="mt-1">Updated {formatDate(packet.updatedAt)}</p></div></div></CardHeader><CardContent className="space-y-4">
    <div className="grid gap-3 text-sm md:grid-cols-2 xl:grid-cols-4"><div className="rounded-xl bg-[#0c1320] p-3"><p className="text-xs text-slate-500">Work order</p><p className="mt-1 font-medium">{packet.workOrderKey}</p><p className="mt-1 text-xs text-slate-400">{packet.claimIds.length} approved claim ref(s)</p></div><div className="rounded-xl bg-[#0c1320] p-3"><p className="text-xs text-slate-500">Final preview</p>{packet.previewUrl ? <a href={packet.previewUrl} target="_blank" rel="noreferrer" className="mt-1 inline-flex items-center gap-1 font-medium text-[#8ad5e7] hover:underline"><Eye className="h-3.5 w-3.5" />Open final preview</a> : <p className="mt-1 font-medium text-amber-200">Missing</p>}<p className="mt-1 truncate font-mono text-[10px] text-slate-500">{packet.previewHash ?? "No SHA-256 fingerprint"}</p></div><div className="rounded-xl bg-[#0c1320] p-3"><p className="text-xs text-slate-500">QA</p><p className="mt-1 font-medium">{qaPassed}/{QA_CHECKS.length} checks passed</p><p className="mt-1 text-xs text-slate-400">{packet.qaResults.length ? "Recorded in retained lineage" : "Not yet recorded"}</p></div><div className="rounded-xl bg-[#0c1320] p-3"><p className="text-xs text-slate-500">Publication</p><p className="mt-1 font-medium text-emerald-200">Not published</p><p className="mt-1 text-xs text-slate-400">No schedule or campaign created</p></div></div>
    {packet.blockedReason && <div className="rounded-xl border border-amber-400/20 bg-amber-400/5 p-3 text-sm text-amber-50"><span className="font-semibold">Current note: </span>{packet.blockedReason}</div>}
    <details className="group rounded-xl border border-white/10 bg-[#0c1320] p-4"><summary className="flex cursor-pointer list-none items-center justify-between gap-3 font-medium"><span className="flex items-center gap-2"><ChevronDown className="h-4 w-4 text-[#8ad5e7]" />Copy, claims, QA and immutable lineage</span><ChevronDown className="h-4 w-4 text-slate-400 transition group-open:rotate-180" /></summary><div className="mt-4 grid gap-4 xl:grid-cols-2"><div className="space-y-4"><div><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">Arabic primary copy</p><p dir="rtl" className="mt-2 whitespace-pre-wrap rounded-lg bg-black/20 p-3 text-sm leading-7 text-slate-200">{packet.arabicCopy}</p></div>{packet.caption && <div><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">Caption</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-300">{packet.caption}</p></div>}<div><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">Packet contract</p><pre className="mt-2 max-h-44 overflow-auto rounded-lg bg-black/20 p-3 text-xs leading-5 text-slate-300">{JSON.stringify(packet.outputSchema, null, 2)}</pre></div></div><div className="space-y-4"><div><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">QA results</p><div className="mt-2 space-y-2">{packet.qaResults.length === 0 ? <p className="text-sm text-slate-500">No QA report recorded.</p> : packet.qaResults.map((result: { check: string; passed: boolean; note: string }) => <div key={result.check} className="rounded-lg bg-white/5 p-2 text-xs"><span className={result.passed ? "font-semibold text-emerald-200" : "font-semibold text-rose-200"}>{result.passed ? "PASS" : "REVISE"}</span><span className="ml-2 text-slate-300">{result.check.replaceAll("_", " ")}</span><p className="mt-1 text-slate-500">{result.note}</p></div>)}</div></div><div><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">Review lineage</p><div className="mt-2 space-y-2">{packet.events.map((event: any) => <div key={event.id} className="rounded-lg bg-white/5 p-2 text-xs"><span className="font-semibold text-slate-200">{event.action.replaceAll("_", " ")}</span>{event.fromStatus || event.toStatus ? <span className="ml-2 text-slate-400">{event.fromStatus ?? "—"} → {event.toStatus ?? "—"}</span> : null}{event.feedback && <p className="mt-1 text-slate-300">{event.feedback}</p>}<p className="mt-1 text-slate-500">{formatDate(event.createdAt)}</p></div>)}</div></div></div></div></details>
    <div className="flex flex-col gap-3 border-t border-white/10 pt-4"><div className="flex flex-wrap gap-2">{canCreate && ["draft", "changes_requested", "rejected"].includes(packet.status) && <Button size="sm" variant="outline" onClick={onRevision} className="border-[#5BA3B8]/40 bg-transparent text-[#a9d6e3] hover:bg-[#5BA3B8]/10 hover:text-white"><FilePenLine className="mr-1.5 h-4 w-4" />Create revision</Button>}{canCreate && packet.status === "draft" && <Button size="sm" onClick={onSubmit} className="bg-[#5BA3B8] text-slate-950 hover:bg-[#82c8d9]"><Send className="mr-1.5 h-4 w-4" />Send for review</Button>}{canQa && packet.status === "in_review" && <Button size="sm" onClick={onQa} className="bg-emerald-300 text-emerald-950 hover:bg-emerald-200"><ClipboardCheck className="mr-1.5 h-4 w-4" />Record manual QA</Button>}{canReview && packet.status === "qa_passed" && <Button size="sm" onClick={onReady} className="bg-violet-200 text-violet-950 hover:bg-violet-100"><BadgeCheck className="mr-1.5 h-4 w-4" />Make Approval Ready</Button>}{canReview && ["in_review", "qa_passed", "approval_ready"].includes(packet.status) && <Button size="sm" variant="outline" onClick={onChanges} className="border-amber-400/30 bg-transparent text-amber-100 hover:bg-amber-400/10 hover:text-white"><PauseCircle className="mr-1.5 h-4 w-4" />Request changes</Button>}{isOwner && packet.status === "approval_ready" && <><Button size="sm" onClick={onApprove} className="bg-emerald-300 text-emerald-950 hover:bg-emerald-200"><CheckCircle2 className="mr-1.5 h-4 w-4" />Approve</Button><Button size="sm" variant="outline" onClick={onReject} className="border-rose-400/30 bg-transparent text-rose-200 hover:bg-rose-400/10 hover:text-white"><XCircle className="mr-1.5 h-4 w-4" />Reject</Button></>}{canStop && !["stopped", "superseded", "approved"].includes(packet.status) && <Button size="sm" variant="outline" onClick={onStop} disabled={stopNote.trim().length < 4} className="border-rose-400/30 bg-transparent text-rose-200 hover:bg-rose-400/10 hover:text-white"><StopCircle className="mr-1.5 h-4 w-4" />Stop</Button>}</div>
      {["in_review", "qa_passed", "approval_ready"].includes(packet.status) && (canReview || isOwner) && <Textarea value={reviewNote} onChange={event => setReviewNote(event.target.value)} className="min-h-20 border-white/10 bg-white/5 text-white" placeholder="Required review, approval or change-request note retained in lineage" />}
      {canStop && !["stopped", "superseded", "approved"].includes(packet.status) && <Input value={stopNote} onChange={event => setStopNote(event.target.value)} className="max-w-2xl border-white/10 bg-white/5 text-white placeholder:text-slate-600" placeholder="Required reason to immediately stop this internal packet" />}
      {canQa && packet.status === "in_review" && <div className="rounded-xl border border-emerald-400/20 bg-emerald-400/5 p-4"><p className="font-medium text-emerald-100">Manual final-preview QA</p><p className="mt-1 text-xs leading-5 text-emerald-100/70">Record all checks against the displayed final preview. A missing preview URL or fingerprint blocks QA.</p><div className="mt-3 grid gap-3 md:grid-cols-2">{QA_CHECKS.map(([check, label]) => <div key={check} className="rounded-lg border border-white/10 bg-black/20 p-3"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={qaControls.qaPasses[check] !== false} onChange={event => qaControls.setQaPasses(current => ({ ...current, [check]: event.target.checked }))} className="accent-emerald-300" />Pass · {label}</label><Input value={qaControls.qaNotes[label] ?? ""} onChange={event => qaControls.setQaNotes(current => ({ ...current, [label]: event.target.value }))} className="mt-2 border-white/10 bg-[#0c1320] text-xs text-white" /></div>)}</div><Textarea value={qaControls.qaFeedback} onChange={event => qaControls.setQaFeedback(event.target.value)} className="mt-3 min-h-20 border-white/10 bg-[#0c1320] text-white" placeholder="QA summary; required if any check fails" /></div>}</div>
  </CardContent></Card>;
}
