import { useEffect, useMemo, useState } from "react";
import { useLocation } from "wouter";
import { ArrowLeft, BadgeCheck, CircleAlert, FileCheck2, LockKeyhole, ShieldAlert, Target } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { toast } from "sonner";

type Answer = { questionNumber: number; scopeType: string; programKey: string | null; answerText: string; decisionStatus: string };
type ProgramReadiness = { key: "spain_dnv" | "malta_mprp"; label: string; answeredCount: number; requiredCount: number; missingQuestions: number[]; unknownQuestions: number[]; isReady: boolean };

export default function MetaAdsStrategyPacket() {
  const [, navigate] = useLocation();
  const utils = trpc.useUtils();
  const { data: access, isLoading: accessLoading } = trpc.marketingSystem.access.useQuery();
  const isOwner = access?.role === "owner";
  const { data, isLoading } = trpc.marketingSystem.getMetaAdsStrategyPacketWorkspace.useQuery(undefined, { enabled: isOwner });
  const saveConfirmation = trpc.marketingSystem.saveMetaAdsStrategyProgramConfirmation.useMutation({ onSuccess: () => { utils.marketingSystem.getMetaAdsStrategyPacketWorkspace.invalidate(); toast.success("Program confirmation saved. The company answer remains preserved as its source reference."); }, onError: error => toast.error(error.message) });
  const propose = trpc.marketingSystem.proposeMetaAdsStrategyPacket.useMutation({ onSuccess: () => { utils.marketingSystem.getMetaAdsStrategyPacketWorkspace.invalidate(); toast.success("Strategy Approval Packet proposed for owner review. Campaigns and spend remain locked."); }, onError: error => toast.error(error.message) });
  const approve = trpc.marketingSystem.approveMetaAdsStrategyPacket.useMutation({ onSuccess: () => { utils.marketingSystem.getMetaAdsStrategyPacketWorkspace.invalidate(); toast.success("Strategy planning packet approved. This does not activate Meta, campaigns, budgets, or spend."); }, onError: error => toast.error(error.message) });
  const [programKey, setProgramKey] = useState<"spain_dnv" | "malta_mprp">("spain_dnv");
  const [questionNumber, setQuestionNumber] = useState<number | null>(null);
  const [answerText, setAnswerText] = useState("");
  const [approvalNote, setApprovalNote] = useState("");

  const readiness = data?.readiness;
  const currentProgram = readiness?.programReadiness.find(program => program.key === programKey) as ProgramReadiness | undefined;
  const currentQuestion = useMemo(() => {
    if (!readiness || !currentProgram) return null;
    const number = questionNumber ?? currentProgram.missingQuestions[0] ?? null;
    return number ? readiness.companyAnswers.find((answer: Answer) => answer.questionNumber === number) : null;
  }, [readiness, currentProgram, questionNumber]);
  const existingProgramAnswer = useMemo(() => currentQuestion ? readiness?.allAnswers.find((answer: Answer) => answer.scopeType === "program" && answer.programKey === programKey && answer.questionNumber === currentQuestion.questionNumber) : null, [readiness, programKey, currentQuestion]);

  useEffect(() => {
    if (!currentQuestion) { setAnswerText(""); return; }
    setAnswerText(existingProgramAnswer?.answerText ?? currentQuestion.answerText);
  }, [currentQuestion?.questionNumber, existingProgramAnswer?.answerText, programKey]);

  const confirmProgramAnswer = () => {
    if (!readiness || !currentQuestion || !answerText.trim()) return toast.error("Confirm or correct the company reference answer before saving this program variation.");
    saveConfirmation.mutate({ sessionId: readiness.session.id, programKey, questionNumber: currentQuestion.questionNumber, answerText, decisionStatus: "answered", attachments: [] });
    setQuestionNumber(null);
  };

  if (accessLoading || (isOwner && isLoading)) return <div className="flex min-h-[65vh] items-center justify-center text-slate-400">Loading Strategy Approval Packet…</div>;
  if (!isOwner) return <div className="mx-auto flex min-h-[65vh] max-w-xl flex-col items-center justify-center px-6 text-center"><LockKeyhole className="mb-4 h-12 w-12 text-amber-300" /><h1 className="text-2xl font-bold text-white">Strategy Approval Packet is owner-controlled</h1><p className="mt-3 text-sm leading-6 text-slate-400">Only Mahmoud can confirm program variations, propose the strategy packet, or record its final planning decision.</p></div>;

  return <div className="min-h-full bg-[#0c1320] px-4 py-6 text-white md:px-8"><div className="mx-auto max-w-5xl space-y-6">
    <section className="rounded-3xl border border-[#C9A84C]/25 bg-[radial-gradient(circle_at_92%_0%,rgba(201,168,76,.18),transparent_40%),linear-gradient(115deg,#182337,#0d1524)] p-6 md:p-8"><div className="flex flex-wrap items-end justify-between gap-5"><div><div className="mb-3 flex items-center gap-2 text-[#EBD990]"><FileCheck2 className="h-4 w-4" /><span className="text-xs font-bold uppercase tracking-[.16em]">Final planning gate · no execution</span></div><h1 className="text-3xl font-semibold tracking-tight">Meta Ads Strategy Approval Packet</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-300">Confirm program-specific variations against the completed company interview, inspect hard blockers, then create a hash-locked strategy planning packet for Mahmoud’s explicit decision.</p></div><Badge variant="outline" className="w-fit border-amber-300/30 bg-amber-300/10 text-amber-100">Meta operations locked</Badge></div></section>

    {!readiness ? <Card className="border-white/10 bg-[#111b2c] text-white"><CardHeader><CardTitle>No Strategy Intake exists yet</CardTitle><CardDescription className="text-slate-400">Complete the owner-only 66-question Strategy Intake before an Approval Packet can be prepared.</CardDescription></CardHeader><CardContent><Button onClick={() => navigate("/marketing/meta-ads-strategy")} className="bg-[#C9A84C] text-[#1A3A5C] hover:bg-[#EBD990]">Open Strategy Intake</Button></CardContent></Card> : <>
      <div className="grid gap-4 md:grid-cols-3"><Card className={`border-white/10 ${readiness.activeBrandBook ? "bg-emerald-400/10" : "bg-amber-400/10"}`}><CardHeader className="pb-3"><CardDescription className="text-slate-400">Brand Book</CardDescription><CardTitle className="text-lg">{readiness.activeBrandBook ? `Active v${readiness.activeBrandBook.version}` : "Blocking"}</CardTitle></CardHeader></Card><Card className={`border-white/10 ${readiness.companyComplete ? "bg-emerald-400/10" : "bg-amber-400/10"}`}><CardHeader className="pb-3"><CardDescription className="text-slate-400">Company interview v{readiness.session.version}</CardDescription><CardTitle className="text-lg">{readiness.companyComplete ? "66 answers confirmed" : `${readiness.missingCompanyQuestions.length + readiness.unknownCompanyQuestions.length} blockers`}</CardTitle></CardHeader></Card><Card className={`border-white/10 ${readiness.isReady ? "bg-emerald-400/10" : "bg-amber-400/10"}`}><CardHeader className="pb-3"><CardDescription className="text-slate-400">Packet readiness</CardDescription><CardTitle className="text-lg">{readiness.isReady ? "Ready to propose" : "Blocked"}</CardTitle></CardHeader></Card></div>

      <Card className="border-white/10 bg-[#111b2c] text-white"><CardHeader><CardTitle>Program confirmation</CardTitle><CardDescription className="text-slate-400">The saved company answer is loaded as a reference. Confirm it or edit it for each program without overwriting the company version.</CardDescription></CardHeader><CardContent className="space-y-5"><div className="grid gap-3 md:grid-cols-2">{readiness.programReadiness.map((program: ProgramReadiness) => <button key={program.key} type="button" onClick={() => { setProgramKey(program.key); setQuestionNumber(null); }} className={`rounded-xl border p-4 text-left ${program.key === programKey ? "border-[#C9A84C]/60 bg-[#C9A84C]/10" : "border-white/10 bg-[#0c1320]"}`}><div className="flex items-center justify-between gap-3"><span className="font-medium">{program.label}</span>{program.isReady ? <Badge className="bg-emerald-500/20 text-emerald-200">Ready</Badge> : <Badge className="bg-amber-500/20 text-amber-100">{program.answeredCount}/{program.requiredCount}</Badge>}</div><p className="mt-2 text-xs leading-5 text-slate-400">{program.isReady ? "All required program assumptions are explicitly confirmed." : `${program.missingQuestions.length} confirmation(s) remain; unknown values cannot enter a packet.`}</p></button>)}</div>
      {currentQuestion ? <div className="space-y-4 rounded-2xl border border-[#5BA3B8]/25 bg-[#0c1320] p-5"><div className="flex items-center justify-between gap-3"><p className="text-xs font-semibold uppercase tracking-[.14em] text-[#a9d6e3]">{programKey === "spain_dnv" ? "Spain Digital Nomad Residency" : "Malta Permanent Residence Programme"}</p><Badge variant="outline" className="border-white/15 text-slate-300">Question {currentQuestion.questionNumber}</Badge></div><p className="text-base leading-7">{readiness.allAnswers.find((answer: Answer) => answer.scopeType === "company" && answer.questionNumber === currentQuestion.questionNumber)?.answerText ? "Confirm or correct the company answer for this program:" : "Company answer reference"}</p><Textarea value={answerText} onChange={event => setAnswerText(event.target.value)} className="min-h-36 border-white/10 bg-[#111b2c] text-white" /><div className="flex flex-wrap justify-between gap-3"><Button variant="outline" onClick={() => { const candidates = currentProgram?.missingQuestions ?? []; const index = candidates.indexOf(currentQuestion.questionNumber); setQuestionNumber(candidates[index + 1] ?? candidates[0] ?? null); }} className="border-white/15 bg-transparent text-slate-200 hover:bg-white/5">Next required confirmation</Button><Button onClick={confirmProgramAnswer} disabled={saveConfirmation.isPending} className="bg-[#C9A84C] text-[#1A3A5C] hover:bg-[#EBD990]">Confirm {programKey === "spain_dnv" ? "Spain DNV" : "Malta MPRP"} answer</Button></div></div> : <div className="rounded-xl border border-emerald-400/25 bg-emerald-400/10 p-4 text-sm text-emerald-100">This program has no remaining confirmation blockers.</div>}</CardContent></Card>

      <Card className="border-white/10 bg-[#111b2c] text-white"><CardHeader><CardTitle>Strategy packet decision</CardTitle><CardDescription className="text-slate-400">An approved packet locks the exact current answers, program confirmations and active Brand Book hash as a planning record. It does not connect Meta or permit campaign operations.</CardDescription></CardHeader><CardContent className="space-y-4">{!readiness.isReady && <div className="flex gap-3 rounded-xl border border-amber-400/25 bg-amber-400/10 p-4 text-sm text-amber-100"><ShieldAlert className="mt-0.5 h-5 w-5 shrink-0" /><div><strong>Packet blocked.</strong><p className="mt-1">Complete the active Brand Book, resolve every company Unknown/missing answer, and confirm all required Spain DNV and Malta MPRP variations.</p></div></div>}{readiness.isReady && data.packets.length === 0 && <Button onClick={() => propose.mutate({ sessionId: readiness.session.id })} disabled={propose.isPending} className="bg-[#C9A84C] text-[#1A3A5C] hover:bg-[#EBD990]">Propose hash-locked Strategy Packet</Button>}{data.packets.map(packet => <div key={packet.id} className="rounded-xl border border-white/10 bg-[#0c1320] p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-semibold">Strategy Packet v{packet.version}</p><p className="mt-1 font-mono text-xs text-slate-500">{packet.packetHash.slice(0, 16)}…</p></div><Badge className={packet.status === "approved" ? "bg-emerald-500/20 text-emerald-200" : "bg-amber-500/20 text-amber-100"}>{packet.status}</Badge></div>{packet.status === "proposed" && <div className="mt-4 space-y-3"><Label htmlFor={`packet-note-${packet.id}`}>Explicit planning approval note</Label><Textarea id={`packet-note-${packet.id}`} value={approvalNote} onChange={event => setApprovalNote(event.target.value)} className="min-h-24 border-white/10 bg-[#111b2c] text-white" placeholder="Record the planning decision, constraints and why this is approved. No campaign activation occurs." /><Button onClick={() => approve.mutate({ packetId: packet.id, ownerNote: approvalNote })} disabled={approvalNote.trim().length < 8 || approve.isPending} className="bg-emerald-500 text-white hover:bg-emerald-400"><BadgeCheck className="mr-2 h-4 w-4" />Approve planning packet only</Button></div>}<p className="mt-4 text-xs leading-5 text-slate-400">Approval is a strategy-version audit decision only. A separate Phase 5b proposal, Meta authorization, explicit budget/spend caps and measurement-pilot approval are still required.</p></div>)}</CardContent></Card>
    </>}
    <Button variant="ghost" onClick={() => navigate("/marketing/meta-ads-strategy")} className="text-slate-400 hover:bg-white/5 hover:text-white"><ArrowLeft className="mr-2 h-4 w-4" />Back to Strategy Intake</Button>
  </div></div>;
}
