import { useMemo } from "react";
import { useLocation } from "wouter";
import { AlertTriangle, ArrowLeft, CheckCircle2, CircleSlash2, ExternalLink, KeyRound, LockKeyhole, PlugZap, RefreshCw, ShieldCheck } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

function statusLabel(state: string) {
  if (state === "managed_internal") return { label: "Managed internally", className: "border-sky-400/30 bg-sky-400/10 text-sky-100" };
  if (state === "server_secret_present") return { label: "Server secret present", className: "border-emerald-400/30 bg-emerald-400/10 text-emerald-100" };
  return { label: "Server secret missing", className: "border-amber-400/30 bg-amber-400/10 text-amber-100" };
}

export default function ProviderConnectionCenter() {
  const [, navigate] = useLocation();
  const access = trpc.marketingSystem.access.useQuery();
  const connectionCenter = trpc.marketingSystem.getProviderConnectionCenter.useQuery(undefined, { refetchOnWindowFocus: false });
  const initializeLock = trpc.marketingSystem.initializeFullAutopilotLock.useMutation({ onSuccess: () => connectionCenter.refetch() });
  const isOwner = ["owner", "marketing_system_admin"].includes(access.data?.role ?? "");
  const missingCount = useMemo(() => connectionCenter.data?.connections.filter(connection => connection.configurationState === "server_secret_missing").length ?? 0, [connectionCenter.data]);

  if (connectionCenter.isLoading || access.isLoading) return <div className="p-8 text-sm text-slate-400">Loading Provider Connection Center…</div>;
  if (connectionCenter.error || access.error) return <div className="p-8 text-sm text-rose-300">Unable to load Provider Connection Center. Your Marketing System role may not include provider-readiness access.</div>;
  const data = connectionCenter.data;
  if (!data) return null;

  return <div className="mx-auto max-w-7xl space-y-6 p-4 md:p-6">
    <div className="flex flex-col gap-4 rounded-3xl border border-sky-400/20 bg-[radial-gradient(circle_at_top_right,_rgba(91,163,184,.16),transparent_44%),#0c1320] p-6 text-white md:flex-row md:items-end md:justify-between">
      <div className="max-w-3xl"><div className="mb-3 flex items-center gap-2 text-sky-200"><PlugZap className="h-4 w-4" /><span className="text-xs font-bold uppercase tracking-[.18em]">AI Agentic Marketing System · Full Autopilot preparation</span></div><h1 className="text-3xl font-semibold tracking-tight">Provider Connection Center</h1><p className="mt-3 text-sm leading-6 text-slate-300">Prepare provider readiness for the requested full-autopilot model. This center is deliberately **configuration-only**: no keys are shown or accepted here, and no provider, campaign, spending, publication, CAPI, CRM or client action can run.</p></div>
      <Button variant="outline" className="border-white/15 bg-white/5 text-white hover:bg-white/10" onClick={() => navigate("/marketing/agentic-system")}><ArrowLeft className="mr-2 h-4 w-4" />AI Agentic Marketing System</Button>
    </div>

    <Card className="border-amber-400/30 bg-amber-400/10 text-white"><CardContent className="flex gap-3 p-4"><LockKeyhole className="mt-0.5 h-5 w-5 shrink-0 text-amber-200" /><div><p className="font-semibold text-amber-100">Full Autopilot remains locked</p><p className="mt-1 text-sm leading-6 text-amber-100/80">{data.safetyNotice}</p></div></CardContent></Card>

    <div className="grid gap-4 lg:grid-cols-[1.1fr_.9fr]">
      <Card className="border-white/10 bg-[#101a2b] text-white"><CardHeader><CardTitle className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-sky-200" />Autopilot gate status</CardTitle><CardDescription className="text-slate-400">Requested mode: Full Autopilot after pilot safeguards.</CardDescription></CardHeader><CardContent><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-white/10 bg-black/15 p-3"><p className="text-xs text-slate-400">Master kill switch</p><p className="mt-1 font-semibold text-amber-200">{data.control?.masterKillSwitchEnabled ?? true ? "Engaged" : "Not engaged"}</p></div><div className="rounded-xl border border-white/10 bg-black/15 p-3"><p className="text-xs text-slate-400">Provider secrets</p><p className="mt-1 font-semibold text-slate-100">{missingCount === 0 ? "Ready for review" : `${missingCount} provider setup gaps`}</p></div><div className="rounded-xl border border-white/10 bg-black/15 p-3"><p className="text-xs text-slate-400">External operations</p><p className="mt-1 font-semibold text-rose-200">Disabled</p></div></div><div className="mt-4 rounded-xl border border-rose-400/20 bg-rose-400/5 p-3"><p className="text-sm font-medium text-rose-100">Blocking conditions</p><ul className="mt-2 list-disc space-y-1 pl-5 text-xs leading-5 text-rose-100/80">{data.autopilot.blockers.map((blocker, index) => <li key={index}>{blocker}</li>)}</ul></div>{isOwner ? <div className="mt-4 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-white/10 bg-white/[.03] p-3"><p className="text-xs leading-5 text-slate-400">Reasserting the lock deliberately engages the master kill switch. It does not create any provider connection.</p><Button size="sm" variant="outline" className="border-amber-400/30 bg-amber-400/10 text-amber-100 hover:bg-amber-400/15" disabled={initializeLock.isPending} onClick={() => initializeLock.mutate()}>{initializeLock.isPending ? <RefreshCw className="mr-2 h-4 w-4 animate-spin" /> : <LockKeyhole className="mr-2 h-4 w-4" />}Keep locked</Button></div> : null}</CardContent></Card>
      <Card className="border-white/10 bg-[#101a2b] text-white"><CardHeader><CardTitle className="flex items-center gap-2"><KeyRound className="h-5 w-5 text-sky-200" />Secure connection process</CardTitle><CardDescription className="text-slate-400">Credentials never go in CRM fields, chat, source code or project files.</CardDescription></CardHeader><CardContent className="space-y-3 text-sm leading-6 text-slate-300"><ol className="list-decimal space-y-2 pl-5"><li>Create least-privileged server-side credentials directly in each provider’s console.</li><li>Configure them as protected server environment secrets, then restart/redeploy the CRM.</li><li>Register the exact signed callback endpoint only after its signature verification and idempotency tests are ready.</li><li>Recheck this center: it reports only presence/absence, never the secret value.</li><li>Complete every listed gate, then review a separate execution-release proposal before enabling one bounded pilot.</li></ol><div className="rounded-xl border border-sky-400/20 bg-sky-400/5 p-3 text-xs text-sky-100/80">The existing ELEVAY ElevenLabs voice adapter is already server-side. It still requires a final approved script and remains inside the future execution gate.</div></CardContent></Card>
    </div>

    <Card className="border-white/10 bg-[#101a2b] text-white"><CardHeader><CardTitle>Provider readiness inventory</CardTitle><CardDescription className="text-slate-400">Status is calculated server-side. The page deliberately hides credential names and values.</CardDescription></CardHeader><CardContent className="grid gap-4 lg:grid-cols-2">{data.connections.map(connection => { const status = statusLabel(connection.configurationState); return <div key={connection.alias} className="rounded-2xl border border-white/10 bg-black/15 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold text-white">{connection.provider}</p><p className="mt-1 text-xs uppercase tracking-[.14em] text-slate-500">{connection.connectionKind.replaceAll("_", " ")}</p></div><Badge variant="outline" className={status.className}>{status.label}</Badge></div><p className="mt-3 text-sm leading-6 text-slate-300">{connection.purpose}</p>{connection.creativeCapabilities.length > 0 ? <div className="mt-3 rounded-xl border border-[#5BA3B8]/20 bg-[#5BA3B8]/5 p-3"><p className="text-xs font-medium text-[#a9d6e3]">Future approved creative scope</p><div className="mt-2 flex flex-wrap gap-1.5">{connection.creativeCapabilities.map(capability => <Badge key={capability} variant="outline" className="border-[#5BA3B8]/25 text-[10px] text-[#bde7ef]">{capability.replaceAll("_", " ")}</Badge>)}</div></div> : null}{connection.webhookPath ? <p className="mt-3 flex items-center gap-1 text-xs text-sky-200"><ExternalLink className="h-3.5 w-3.5" />Reserved signed callback: {connection.webhookPath}</p> : <p className="mt-3 flex items-center gap-1 text-xs text-slate-500"><CircleSlash2 className="h-3.5 w-3.5" />No external callback required</p>}<div className="mt-3 flex items-start gap-2 rounded-xl border border-white/5 bg-white/[.03] p-3 text-xs leading-5 text-slate-400"><AlertTriangle className="mt-0.5 h-3.5 w-3.5 shrink-0 text-amber-200" />{connection.executionBoundary}</div></div>})}</CardContent></Card>

    <Card className="border-white/10 bg-[#101a2b] text-white"><CardHeader><CardTitle>Required gates before any future execution review</CardTitle></CardHeader><CardContent><div className="grid gap-3 md:grid-cols-2">{data.autopilot.requiredGates.map((gate, index) => <div key={gate} className="flex gap-3 rounded-xl border border-white/10 bg-black/15 p-3"><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-sky-400/10 text-xs font-bold text-sky-200">{index + 1}</span><p className="text-sm leading-6 text-slate-300">{gate}</p></div>)}</div></CardContent></Card>
  </div>;
}
