/** Arabic UI translations for the Caribbean citizenship due-diligence questionnaire. */
export const CARIBBEAN_QUESTIONNAIRE_ARABIC: Record<string, string> = {
  "1. Have you ever been arrested, charged, convicted, found guilty, or had an offence expunged in any country, except minor traffic citations?": "1. هل سبق أن تم القبض عليك أو توجيه اتهام إليك أو إدانتك أو ثبوت إدانتك، أو شطب أي جريمة من سجلك في أي دولة، باستثناء مخالفات المرور البسيطة؟",
  "10. Have you ever been sentenced to detention or been on probation?": "10. هل سبق أن صدر بحقك حكم بالاحتجاز أو خضعت للمراقبة القضائية؟",
  "11. Have you ever received a pardon for any criminal offence?": "11. هل سبق أن حصلت على عفو عن أي جريمة جنائية؟",
  "12. Have you ever had a civil or criminal record expunged or sealed by court order?": "12. هل سبق أن شُطب أو أُغلق سجلك المدني أو الجنائي بأمر من المحكمة؟",
  "13. Have you ever been subpoenaed to testify before a federal, state, or county grand jury, board, or commission?": "13. هل سبق أن تم استدعاؤك بموجب أمر قضائي للإدلاء بشهادتك أمام هيئة محلفين كبرى اتحادية أو على مستوى الولاية أو المقاطعة، أو أمام مجلس أو لجنة؟",
  "14. Has a criminal indictment, information, or complaint ever been returned against you without arrest, or named you as an unindicted co-party?": "14. هل سبق أن وُجّهت ضدك لائحة اتهام جنائية أو إخطار اتهام أو شكوى دون إلقاء القبض عليك، أو سُمّيت طرفاً مشاركاً غير متهم؟",
  "15. Have you, as an individual, owner, partner, director, or officer, ever been party to a lawsuit as plaintiff or defendant, other than divorce?": "15. هل سبق أن كنت، بصفتك فرداً أو مالكاً أو شريكاً أو مديراً أو مسؤولاً، طرفاً في دعوى قضائية كمدعٍ أو مدعى عليه، بخلاف دعاوى الطلاق؟",
  "16. Have you ever been involved directly or indirectly in financing terrorism or in any terrorist or criminal organisation?": "16. هل سبق أن شاركت، بصورة مباشرة أو غير مباشرة، في تمويل الإرهاب أو في أي منظمة إرهابية أو إجرامية؟",
  "17. Have you ever been unlawfully present in, deported from, or assisted others to enter or remain unlawfully in any country?": "17. هل سبق أن أقمت بصورة غير قانونية في أي دولة، أو رُحِّلت منها، أو ساعدت آخرين على دخول أي دولة أو البقاء فيها بصورة غير قانونية؟",
  "18. Have you ever applied for citizenship in any country where citizenship was not granted?": "18. هل سبق أن تقدمت بطلب للحصول على الجنسية في أي دولة ولم تُمنح فيها الجنسية؟",
  "19. Have you ever been subject to an order, judgment, or decree limiting your right to engage in a professional or business practice?": "19. هل سبق أن خضعت لأمر أو حكم أو قرار يحد من حقك في مزاولة مهنة أو نشاط تجاري؟",
  "2. Have you ever been denied a visa to a country with which the country you are applying for has visa-free access, without later successfully obtaining that visa?": "2. هل سبق أن رُفضت لك تأشيرة إلى دولة تتمتع الدولة التي تتقدم بطلب إليها بإعفاء من التأشيرة معها، من دون أن تحصل لاحقاً على تلك التأشيرة بنجاح؟",
  "20. Are you a Politically Exposed Person (PEP), a family member, or a close associate of a PEP?": "20. هل أنت شخص معرّض سياسياً (PEP)، أو أحد أفراد أسرة شخص معرّض سياسياً، أو شريك مقرّب له؟",
  "21. Have you ever been declared mentally incapacitated by a court or qualified health practitioner?": "21. هل سبق أن أعلنت محكمة أو ممارس صحي مؤهل أنك غير قادر ذهنياً؟",
  "22. Are there any other business activities in which you are engaged that have not already been disclosed in this form?": "22. هل توجد أي أنشطة تجارية أخرى تمارسها ولم يُفصح عنها مسبقاً في هذا النموذج؟",
  "23. To the best of your knowledge, have you ever been under investigation by a law-enforcement agency or tax authority in any country?": "23. حسب علمك، هل سبق أن كنت محل تحقيق من جهة إنفاذ قانون أو سلطة ضريبية في أي دولة؟",
  "24. I confirm that my wealth has been obtained from completely legitimate sources and is not directly or indirectly the proceeds of criminal activity.": "24. أؤكد أن ثروتي تم الحصول عليها من مصادر مشروعة بالكامل، وأنها ليست، بصورة مباشرة أو غير مباشرة، من عائدات نشاط إجرامي.",
  "25. I confirm that I am fully compliant with my national, regional, and global tax obligations.": "25. أؤكد أنني ملتزم التزاماً كاملاً بواجباتي الضريبية الوطنية والإقليمية والعالمية.",
  "3. Have you ever had a visa cancelled?": "3. هل سبق أن أُلغيت لك تأشيرة؟",
  "4. Have you ever been declared bankrupt by a court?": "4. هل سبق أن أعلنتك محكمة مفلساً؟",
  "5. Have you ever been involved personally, or as a director, in bankruptcy, insolvency, or liquidation proceedings?": "5. هل سبق أن شاركت شخصياً، أو بصفتك مديراً، في إجراءات إفلاس أو إعسار أو تصفية؟",
  "6. Have you ever testified before a grand jury, investigative hearing, or probe?": "6. هل سبق أن أدليت بشهادتك أمام هيئة محلفين كبرى أو جلسة استماع تحقيقية أو تحقيق؟",
  "7. Have any charges or accusations of illegal activity of any nature been made against you in any country?": "7. هل وُجّهت ضدك في أي دولة أي تهم أو ادعاءات بنشاط غير قانوني من أي نوع؟",
  "8. Have you ever been the subject of a criminal investigation?": "8. هل سبق أن كنت محل تحقيق جنائي؟",
  "9. Have you ever been considered a potential national security risk in any country?": "9. هل سبق أن اعتُبرت خطراً محتملاً على الأمن القومي في أي دولة؟",
  "Add another address": "إضافة عنوان آخر",
  "Add another brother or sister": "إضافة أخ أو أخت آخر/أخرى",
  "Add another child": "إضافة طفل آخر",
  "Add another education record": "إضافة سجل تعليمي آخر",
  "Add another employment record": "إضافة سجل وظيفي آخر",
  "Add another licence": "إضافة ترخيص مهني آخر",
  "Add another previous spouse": "إضافة زوج/زوجة سابقة أخرى",
  "Addresses where you have lived during the past 10 years, starting with your current residence": "العناوين التي أقمت فيها خلال السنوات العشر الماضية، بدءاً من محل إقامتك الحالي",
  "Alive": "على قيد الحياة",
  "All education and qualifications obtained": "جميع المؤهلات والتحصيلات التعليمية التي تم الحصول عليها",
  "All employment history, unemployment periods, and active or inactive self-employed companies": "كامل السجل الوظيفي وفترات البطالة والشركات المملوكة ذاتياً النشطة أو غير النشطة",
  "All spouse employment history, unemployment periods, and active or inactive self-employed companies": "كامل السجل الوظيفي للزوج/الزوجة وفترات البطالة والشركات المملوكة ذاتياً النشطة أو غير النشطة",
  "Application": "الطلب",
  "Are any children or other dependants included in this application?": "هل يُدرج أي أطفال أو معالون آخرون في هذا الطلب؟",
  "Average annual net income in US dollars during the past three years": "متوسط صافي الدخل السنوي بالدولار الأمريكي خلال السنوات الثلاث الماضية",
  "Brothers and sisters, including half, step, and adopted siblings": "الإخوة والأخوات، بمن فيهم الإخوة غير الأشقاء وإخوة الزوج/الزوجة والإخوة بالتبني",
  "Business address": "عنوان العمل",
  "Business assets (USD)": "أصول الأعمال (USD)",
  "Business fax number": "رقم فاكس العمل",
  "Business telephone number": "رقم هاتف العمل",
  "Child": "طفل",
  "Children": "الأطفال",
  "Citizenship": "الجنسية",
  "Citizenship at birth": "الجنسية عند الولادة",
  "City and country": "المدينة والدولة",
  "College / University": "الكلية / الجامعة",
  "Company address": "عنوان الشركة",
  "Company fax number": "رقم فاكس الشركة",
  "Company telephone number": "رقم هاتف الشركة",
  "Complete address": "العنوان الكامل",
  "Complete residential address": "عنوان السكن الكامل",
  "Country of residence": "دولة الإقامة",
  "Current occupation": "المهنة الحالية",
  "Current residential address": "عنوان السكن الحالي",
  "Current spouse date of birth": "تاريخ ميلاد الزوج/الزوجة الحالي/ة",
  "Current spouse full name after marriage": "الاسم الكامل للزوج/الزوجة الحالي/ة بعد الزواج",
  "Current spouse full name before marriage": "الاسم الكامل للزوج/الزوجة الحالي/ة قبل الزواج",
  "Current spouse place of birth": "مكان ميلاد الزوج/الزوجة الحالي/ة",
  "Current total personal net assets in US dollars": "إجمالي صافي الأصول الشخصية الحالية بالدولار الأمريكي",
  "Date held / validity period": "تاريخ حيازة الوثيقة / مدة الصلاحية",
  "Date of birth": "تاريخ الميلاد",
  "Date of current marriage": "تاريخ الزواج الحالي",
  "Date of divorce": "تاريخ الطلاق",
  "Date of marriage": "تاريخ الزواج",
  "Date since father has resided at the current address": "تاريخ إقامة الأب في العنوان الحالي",
  "Date since mother has resided at the current address": "تاريخ إقامة الأم في العنوان الحالي",
  "Date since residing at the current address": "تاريخ الإقامة في العنوان الحالي",
  "Date since residing at the permanent address": "تاريخ الإقامة في العنوان الدائم",
  "Date since spouse has resided at the current address": "تاريخ إقامة الزوج/الزوجة في العنوان الحالي",
  "Date since spouse has resided at the permanent address": "تاريخ إقامة الزوج/الزوجة في العنوان الدائم",
  "Deceased": "متوفى",
  "Declaration and Signature": "الإقرار والتوقيع",
  "Declarations": "الإقرارات",
  "Distinguishing marks": "علامات مميزة",
  "Driving licence expiry date": "تاريخ انتهاء رخصة القيادة",
  "Driving licence number and issuing country": "رقم رخصة القيادة ودولة الإصدار",
  "Education history for the spouse and every included dependant": "السجل التعليمي للزوج/الزوجة ولكل معال مُدرج",
  "Education level": "المستوى التعليمي",
  "Elementary": "المرحلة الابتدائية",
  "Email address": "عنوان البريد الإلكتروني",
  "Emergency Contact": "جهة اتصال للطوارئ",
  "Emergency contact complete address": "العنوان الكامل لجهة اتصال الطوارئ",
  "Emergency contact email": "البريد الإلكتروني لجهة اتصال الطوارئ",
  "Emergency contact full name": "الاسم الكامل لجهة اتصال الطوارئ",
  "Emergency contact relationship to you": "صلة جهة اتصال الطوارئ بك",
  "Emergency contact telephone or mobile number": "رقم هاتف أو هاتف محمول لجهة اتصال الطوارئ",
  "Employer / company": "صاحب العمل / الشركة",
  "Enter N/A when not applicable.": "أدخل N/A عندما لا ينطبق الأمر.",
  "Estimated net worth (assets minus liabilities in USD)": "صافي الثروة التقديري (الأصول ناقص الخصوم بالدولار الأمريكي)",
  "Explain in detail why you are seeking an alternative citizenship": "اشرح بالتفصيل سبب سعيك للحصول على جنسية بديلة",
  "Eye colour": "لون العينين",
  "Family Included in Application": "الأسرة المُدرجة في الطلب",
  "Father's citizenship": "جنسية الأب",
  "Father's complete residential address": "عنوان السكن الكامل للأب",
  "Father's current occupation": "المهنة الحالية للأب",
  "Father's date of birth": "تاريخ ميلاد الأب",
  "Father's date of marriage": "تاريخ زواج الأب",
  "Father's first / given name": "الاسم الأول / الاسم الشخصي للأب",
  "Father's home telephone number": "رقم هاتف المنزل للأب",
  "Father's mobile number": "رقم الهاتف المحمول للأب",
  "Father's passport issuing country": "دولة إصدار جواز سفر الأب",
  "Father's passport number": "رقم جواز سفر الأب",
  "Father's place and country of birth": "مكان ودولة ميلاد الأب",
  "Father's place and country of marriage": "مكان ودولة زواج الأب",
  "Father's surname / family name": "اسم عائلة الأب / اللقب",
  "Fax number": "رقم الفاكس",
  "First / Given Name": "الاسم الأول / الاسم الشخصي",
  "Fixed assets (USD)": "الأصول الثابتة (USD)",
  "From": "من",
  "Full name after marriage": "الاسم الكامل بعد الزواج",
  "Full name before marriage": "الاسم الكامل قبل الزواج",
  "Gender": "الجنس",
  "Hair colour": "لون الشعر",
  "Has the spouse ever had disciplinary action related to a professional licence?": "هل سبق أن تعرض الزوج/الزوجة لإجراء تأديبي متعلق بترخيص مهني؟",
  "Have any disciplinary actions ever been taken against you in relation to a professional licence?": "هل سبق اتخاذ أي إجراءات تأديبية ضدك فيما يتعلق بترخيص مهني؟",
  "Height": "الطول",
  "High School": "المدرسة الثانوية",
  "Home telephone number": "رقم هاتف المنزل",
  "I acknowledge the visa-refusal, compatible-visa, full-disclosure, adverse-history, company-document, and professional-licence undertakings stated in this questionnaire.": "أقرّ بأنني اطلعت على التعهدات الواردة في هذا الاستبيان بشأن رفض التأشيرة والتأشيرة المتوافقة والإفصاح الكامل والسجل السلبي ووثائق الشركة والتراخيص المهنية.",
  "I declare that the information provided is true and correct, and I undertake to inform ELEVAY immediately of any change.": "أصرّح بأن المعلومات المقدمة صحيحة ودقيقة، وأتعهد بإبلاغ ELEVAY فوراً بأي تغيير.",
  "Identity card number and issuing country": "رقم بطاقة الهوية ودولة الإصدار",
  "If Yes, provide the full date, place, authority, outcome, and explanation.": "إذا كانت الإجابة نعم، يُرجى تقديم التاريخ الكامل والمكان والجهة المختصة والنتيجة والشرح.",
  "Investments such as stocks, shares, bonds, and debentures (USD)": "استثمارات مثل الأسهم والحصص والسندات وسندات الدين (USD)",
  "Is a spouse included in this citizenship application?": "هل يُدرج زوج/زوجة في طلب الجنسية هذا؟",
  "Is the father alive or deceased?": "هل الأب على قيد الحياة أم متوفى؟",
  "Issuing country": "دولة الإصدار",
  "Languages the spouse speaks and writes": "اللغات التي يتحدثها الزوج/الزوجة ويكتبها",
  "Languages you speak and write, including level (Native, Fluent, or Basic)": "اللغات التي تتحدثها وتكتبها، بما في ذلك المستوى (لغة أم، بطلاقة، أو أساسي)",
  "Licence name": "اسم الترخيص",
  "Licence number": "رقم الترخيص",
  "Licensing body": "جهة الترخيص",
  "List all valid and expired professional licences": "اذكر جميع التراخيص المهنية السارية والمنتهية",
  "List the spouse's valid and expired professional licences": "اذكر التراخيص المهنية السارية والمنتهية للزوج/الزوجة",
  "Main Applicant · Address History": "مقدم الطلب الرئيسي · سجل العناوين",
  "Main Applicant · Address and Contact": "مقدم الطلب الرئيسي · العنوان وبيانات الاتصال",
  "Main Applicant · Business": "مقدم الطلب الرئيسي · الأعمال",
  "Main Applicant · Education": "مقدم الطلب الرئيسي · التعليم",
  "Main Applicant · Employment": "مقدم الطلب الرئيسي · التوظيف",
  "Main Applicant · Employment History": "مقدم الطلب الرئيسي · السجل الوظيفي",
  "Main Applicant · Family Information": "مقدم الطلب الرئيسي · معلومات الأسرة",
  "Main Applicant · Family Information · Parents": "مقدم الطلب الرئيسي · معلومات الأسرة · الوالدان",
  "Main Applicant · Family Information · Paternal Grandparents": "مقدم الطلب الرئيسي · معلومات الأسرة · الأجداد من جهة الأب",
  "Main Applicant · Personal Information": "مقدم الطلب الرئيسي · المعلومات الشخصية",
  "Main Applicant · Previous Spouse": "مقدم الطلب الرئيسي · الزوج/الزوجة السابقة",
  "Main Applicant · Professional Licences": "مقدم الطلب الرئيسي · التراخيص المهنية",
  "Main Applicant · Source of Income": "مقدم الطلب الرئيسي · مصدر الدخل",
  "Main Applicant · Spouse Details": "مقدم الطلب الرئيسي · تفاصيل الزوج/الزوجة",
  "Main geographical jurisdictions in which your business is conducted": "النطاقات الجغرافية الرئيسية التي تُزاول فيها أعمالك",
  "Main jurisdictions in which the spouse's business is conducted": "النطاقات القضائية الرئيسية التي تُزاول فيها أعمال الزوج/الزوجة",
  "Main sources of income": "مصادر الدخل الرئيسية",
  "Marital status": "الحالة الاجتماعية",
  "Masters / PhD": "ماجستير / دكتوراه",
  "Mobile number": "رقم الهاتف المحمول",
  "More than USD 1,000,000": "أكثر من USD 1,000,000",
  "More than USD 10,000,000": "أكثر من USD 10,000,000",
  "More than USD 100,000": "أكثر من USD 100,000",
  "More than USD 2,000,000": "أكثر من USD 2,000,000",
  "More than USD 500,000": "أكثر من USD 500,000",
  "Most important persons or companies with whom the business trades": "أهم الأشخاص أو الشركات التي تتعامل معها الأعمال التجارية",
  "Most important persons or companies with whom the spouse does business": "أهم الأشخاص أو الشركات الذين يتعامل معهم الزوج/الزوجة في الأعمال",
  "Most important persons or companies with whom the spouse's business trades": "أهم الأشخاص أو الشركات التي تتعامل معها أعمال الزوج/الزوجة",
  "Most important persons or companies with whom you do business": "أهم الأشخاص أو الشركات التي تتعامل معهم تجارياً",
  "Mother's citizenship": "جنسية الأم",
  "Mother's complete residential address": "عنوان السكن الكامل للأم",
  "Mother's current occupation": "المهنة الحالية للأم",
  "Mother's date of birth": "تاريخ ميلاد الأم",
  "Mother's first / given name": "الاسم الأول / الاسم الشخصي للأم",
  "Mother's passport issuing country": "دولة إصدار جواز سفر الأم",
  "Mother's passport number": "رقم جواز سفر الأم",
  "Mother's place and country of birth": "مكان ودولة ميلاد الأم",
  "Mother's surname / family name": "اسم عائلة الأم / اللقب",
  "Name of business": "اسم النشاط التجاري",
  "Name of company": "اسم الشركة",
  "Name of school": "اسم المدرسة",
  "Nature of business": "طبيعة النشاط التجاري",
  "Nature of the spouse's business": "طبيعة أعمال الزوج/الزوجة",
  "Occupation": "المهنة",
  "Occupation by training": "المهنة بحسب التأهيل",
  "Other citizenship": "جنسية أخرى",
  "Other dependant": "معال آخر",
  "Other names / known as": "أسماء أخرى / معروف باسم",
  "Other names or aliases": "أسماء أخرى أو أسماء مستعارة",
  "Other telephone number": "رقم هاتف آخر",
  "Outstanding long-term loans, including mortgage, car, or personal loans": "القروض طويلة الأجل المستحقة، بما في ذلك الرهن العقاري أو قرض السيارة أو القروض الشخصية",
  "Outstanding short-term liabilities, including credit cards or tax liability": "الالتزامات قصيرة الأجل المستحقة، بما في ذلك بطاقات الائتمان أو الالتزامات الضريبية",
  "Passport number": "رقم جواز السفر",
  "Paternal grandfather's date of birth": "تاريخ ميلاد الجد من جهة الأب",
  "Paternal grandfather's first / given name": "الاسم الأول / الاسم الشخصي للجد من جهة الأب",
  "Paternal grandfather's place and country of birth": "مكان ودولة ميلاد الجد من جهة الأب",
  "Paternal grandfather's surname / family name": "اسم عائلة الجد من جهة الأب / اللقب",
  "Paternal grandmother's date of birth": "تاريخ ميلاد الجدة من جهة الأب",
  "Paternal grandmother's first / given name": "الاسم الأول / الاسم الشخصي للجدة من جهة الأب",
  "Paternal grandmother's place and country of birth": "مكان ودولة ميلاد الجدة من جهة الأب",
  "Paternal grandmother's surname / family name": "اسم عائلة الجدة من جهة الأب / اللقب",
  "Period of marriage in years and months": "مدة الزواج بالسنوات والأشهر",
  "Permanent residential address": "عنوان السكن الدائم",
  "Permanent telephone number / home landline": "رقم الهاتف الدائم / الخط الأرضي للمنزل",
  "Person's full name": "الاسم الكامل للشخص",
  "Place and country of birth": "مكان ودولة الميلاد",
  "Place of birth": "مكان الميلاد",
  "Place of current marriage": "مكان الزواج الحالي",
  "Place of marriage": "مكان الزواج",
  "Present citizenship": "الجنسية الحالية",
  "Previous spouse details": "تفاصيل الزوج/الزوجة السابقة",
  "Qualification / diploma obtained": "المؤهل / الدبلوم الذي تم الحصول عليه",
  "Real estate holdings (USD)": "العقارات المملوكة (USD)",
  "Relationship": "صلة القرابة",
  "Savings and deposits (USD)": "المدخرات والودائع (USD)",
  "Select Yes to confirm this declaration.": "اختر نعم لتأكيد هذا الإقرار.",
  "Social Security number and issuing country": "رقم الضمان الاجتماعي ودولة الإصدار",
  "Spouse": "الزوج/الزوجة",
  "Spouse Social Security number and issuing country": "رقم الضمان الاجتماعي للزوج/الزوجة ودولة الإصدار",
  "Spouse addresses during the past 10 years, starting with the current residence": "عناوين الزوج/الزوجة خلال السنوات العشر الماضية، بدءاً من محل الإقامة الحالي",
  "Spouse and Dependants · Education": "الزوج/الزوجة والمعالون · التعليم",
  "Spouse average annual net income in USD during the past three years": "متوسط صافي الدخل السنوي للزوج/الزوجة بالدولار الأمريكي خلال السنوات الثلاث الماضية",
  "Spouse business address": "عنوان عمل الزوج/الزوجة",
  "Spouse business assets (USD)": "أصول أعمال الزوج/الزوجة (USD)",
  "Spouse business fax number": "رقم فاكس عمل الزوج/الزوجة",
  "Spouse business name": "اسم أعمال الزوج/الزوجة",
  "Spouse business telephone number": "رقم هاتف عمل الزوج/الزوجة",
  "Spouse citizenship at birth": "جنسية الزوج/الزوجة عند الولادة",
  "Spouse company address": "عنوان شركة الزوج/الزوجة",
  "Spouse company fax number": "رقم فاكس شركة الزوج/الزوجة",
  "Spouse company name": "اسم شركة الزوج/الزوجة",
  "Spouse company telephone number": "رقم هاتف شركة الزوج/الزوجة",
  "Spouse current occupation": "المهنة الحالية للزوج/الزوجة",
  "Spouse current residential address": "عنوان السكن الحالي للزوج/الزوجة",
  "Spouse current total personal net assets in USD": "إجمالي صافي الأصول الشخصية الحالية للزوج/الزوجة بالدولار الأمريكي",
  "Spouse date of birth": "تاريخ ميلاد الزوج/الزوجة",
  "Spouse distinguishing marks": "علامات مميزة للزوج/الزوجة",
  "Spouse driving licence expiry date": "تاريخ انتهاء رخصة قيادة الزوج/الزوجة",
  "Spouse driving licence number and issuing country": "رقم رخصة قيادة الزوج/الزوجة ودولة الإصدار",
  "Spouse email address": "عنوان البريد الإلكتروني للزوج/الزوجة",
  "Spouse estimated net worth in USD": "صافي الثروة التقديري للزوج/الزوجة بالدولار الأمريكي",
  "Spouse eye colour": "لون عيني الزوج/الزوجة",
  "Spouse fax number": "رقم فاكس الزوج/الزوجة",
  "Spouse first / given name": "الاسم الأول / الاسم الشخصي للزوج/الزوجة",
  "Spouse fixed assets (USD)": "الأصول الثابتة للزوج/الزوجة (USD)",
  "Spouse hair colour": "لون شعر الزوج/الزوجة",
  "Spouse height": "طول الزوج/الزوجة",
  "Spouse home telephone number": "رقم هاتف منزل الزوج/الزوجة",
  "Spouse identity card number and issuing country": "رقم بطاقة هوية الزوج/الزوجة ودولة الإصدار",
  "Spouse investments (USD)": "استثمارات الزوج/الزوجة (USD)",
  "Spouse main sources of income": "مصادر الدخل الرئيسية للزوج/الزوجة",
  "Spouse mobile number": "رقم الهاتف المحمول للزوج/الزوجة",
  "Spouse occupation by training": "مهنة الزوج/الزوجة بحسب التأهيل",
  "Spouse other citizenship": "جنسية أخرى للزوج/الزوجة",
  "Spouse other names or aliases": "أسماء أخرى أو أسماء مستعارة للزوج/الزوجة",
  "Spouse other telephone number": "رقم هاتف آخر للزوج/الزوجة",
  "Spouse outstanding long-term loans": "القروض طويلة الأجل المستحقة للزوج/الزوجة",
  "Spouse outstanding short-term liabilities": "الالتزامات قصيرة الأجل المستحقة للزوج/الزوجة",
  "Spouse permanent residential address": "عنوان السكن الدائم للزوج/الزوجة",
  "Spouse place and country of birth": "مكان ودولة ميلاد الزوج/الزوجة",
  "Spouse present citizenship": "الجنسية الحالية للزوج/الزوجة",
  "Spouse real estate holdings (USD)": "العقارات المملوكة للزوج/الزوجة (USD)",
  "Spouse savings and deposits (USD)": "مدخرات وودائع الزوج/الزوجة (USD)",
  "Spouse surname / family name": "اسم عائلة الزوج/الزوجة / اللقب",
  "Spouse total liabilities (USD)": "إجمالي الخصوم للزوج/الزوجة (USD)",
  "Spouse weight": "وزن الزوج/الزوجة",
  "Spouse · Address History": "الزوج/الزوجة · سجل العناوين",
  "Spouse · Address and Contact": "الزوج/الزوجة · العنوان وبيانات الاتصال",
  "Spouse · Business": "الزوج/الزوجة · الأعمال",
  "Spouse · Employment": "الزوج/الزوجة · التوظيف",
  "Spouse · Employment History": "الزوج/الزوجة · السجل الوظيفي",
  "Spouse · Family Information": "الزوج/الزوجة · معلومات الأسرة",
  "Spouse · Family Information · Parents": "الزوج/الزوجة · معلومات الأسرة · الوالدان",
  "Spouse · Family Information · Paternal Grandparents": "الزوج/الزوجة · معلومات الأسرة · الأجداد من جهة الأب",
  "Spouse · Personal Information": "الزوج/الزوجة · المعلومات الشخصية",
  "Spouse · Previous Spouse": "الزوج/الزوجة · الزوج/الزوجة السابقة",
  "Spouse · Professional Licences": "الزوج/الزوجة · التراخيص المهنية",
  "Spouse · Source of Income": "الزوج/الزوجة · مصدر الدخل",
  "Spouse's brothers and sisters, including half, step, and adopted siblings": "إخوة وأخوات الزوج/الزوجة، بمن فيهم الإخوة غير الأشقاء وإخوة الزوج/الزوجة والإخوة بالتبني",
  "Spouse's previous spouse details": "تفاصيل الزوج/الزوجة السابقة للزوج/الزوجة",
  "Street, building/villa, town/city, postal code, and country": "الشارع، المبنى/الفيلا، البلدة/المدينة، الرمز البريدي، والدولة",
  "Summarise how the spouse accumulated total net worth": "لخّص كيفية تراكم إجمالي صافي ثروة الزوج/الزوجة",
  "Summarise how you accumulated your total net worth, including main acquisitions, disposals, and events": "لخّص كيفية تراكم إجمالي صافي ثروتك، بما في ذلك أهم عمليات الاستحواذ والتصرفات والأحداث",
  "Surname / Family Name": "اسم العائلة / اللقب",
  "To": "إلى",
  "Total liabilities (USD)": "إجمالي الخصوم (USD)",
  "Type of business": "نوع النشاط التجاري",
  "Undertakings and Pledges": "التعهدات والإقرارات",
  "Weight": "الوزن",
};

/** Returns the Arabic questionnaire translation, or the English input when no mapping exists. */
export function questionnaireArabic(value: string): string {
  return CARIBBEAN_QUESTIONNAIRE_ARABIC[value] ?? value;
}
